Repository cockpit-project/cockpit, pull requests merged in 2019-10, with the labels that each got.

#12897 package.json: Pin down eslint-plugin-react
  package.json
Labels: no-test

#12901 Switch zanata to rhel-7.8 branch
  po/zanata.xml
Labels: no-test

#12905 build: Don't clobber an existing bots checkout
  Makefile.am
  autogen.sh
Labels: no-test, release-blocker

#12895 a11y: Add `lang` attribute to every iframe's html tag
  pkg/shell/base_index.js
  test/verify/check-pages
Labels: unrelated-test-failure

#12908 build: Support CI testing against a bots project PR
  Makefile.am
  autogen.sh
Labels: no-test

#12914 package.json: Update mustache package dependency
  package.json
Labels: bot

#12909 lib/page: Override PF4 to (temporarily) fix wrapping
  pkg/lib/page.css
Labels: unrelated-test-failure

#12920 tools: Introduce make-bots script
  Makefile.am
  autogen.sh
  tools/make-bots
Labels: no-test

#12925 tests: Always prepare bots
  test/run
Labels: no-test

#12924 containers: Drop obsolete handling of bots Semaphore unit tests
  containers/unit-tests/run.sh
Labels: no-test

#12868 polkitagent, loopback: Port deprecated GSimpleAsyncResult to GTask
  src/bridge/cockpitpolkitagent.c
  src/common/cockpitloopback.c
Labels: unrelated-test-failure

#12923 machines: Translate modal titles
  pkg/machines/components/create-vm-dialog/createVmDialog.jsx
  pkg/machines/components/diskAdd.jsx
  pkg/machines/components/nicAdd.jsx
  pkg/machines/components/storagePools/createStoragePoolDialog.jsx
  pkg/machines/components/storagePools/storageVolumeCreate.jsx
Labels: unrelated-test-failure

#12922 package.json: Update bootstrap-select package dependency
  package.json
Labels: bot

#12927 package.json: Unpin eslint-plugin-react
  package.json
Labels: no-test

#12929 test: Prepare bots at beginning of test/run
  test/run
  tools/make-bots
Labels: backport, no-test

#12620 packagekit, systemd: Use notifications for available updates info
  pkg/packagekit/manifest.json.in
  pkg/packagekit/updates.jsx
  pkg/systemd/host.css
  pkg/systemd/host.js
  pkg/systemd/index.html
  test/verify/check-active-pages
  test/verify/check-dashboard
  test/verify/check-multi-machine-key
  test/verify/check-packagekit
Labels: release-note

#12928 Update translations from Fedora Zanata
  po/ca.po
  po/cs.po
  po/es.po
  po/fi.po
  po/fr.po
  po/it.po
  po/ja.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
Labels: bot

#12931 build: Distribute package-lock.json in release tarballs
  Makefile.am
Labels: no-test

#12934 test: Prepare bots at beginning of test/run
  test/run
  tools/make-bots
Labels: backport, no-test

#12933 test: Prepare bots at beginning of test/run
  test/run
  tools/make-bots
Labels: backport, no-test

#12944 build: Fix building of react-core-base.css
  src/base1/Makefile.am
Labels: release-blocker

#12942 test: Prepare bots at beginning of test/run
  test/run
  tools/make-bots
Labels: backport

#12579 Searching with keywords
  doc/guide/packages.xml
  pkg/apps/manifest.json.in
  pkg/kdump/manifest.json.in
  pkg/machines/manifest.json.in
  pkg/networkmanager/manifest.json.in
  pkg/packagekit/manifest.json.in
  pkg/selinux/manifest.json.in
  pkg/shell/base_index.js
  pkg/shell/index.html
  pkg/shell/indexes.js
  pkg/shell/switcher.less
  pkg/sosreport/manifest.json.in
  pkg/storaged/manifest.json.in
  pkg/systemd/manifest.json.in
  pkg/users/manifest.json.in
  po/manifest2po
  test/verify/check-pages
Labels: release-note

#12941 test: Disable packagekit preloading in some more cases
  test/verify/check-dashboard
  test/verify/check-multi-machine
  test/verify/check-multi-machine-key
  test/verify/check-shutdown-restart
  test/verify/hacklib.py
Labels: release-blocker, unrelated-test-failure

#12970 package.json: Update patternfly-react package dependency
  package.json
Labels: bot

#12961 tests: CentOS can manage docker storage
  test/verify/check-docker-storage
Labels: no-test

#12884 firewall: ui restructuring
  pkg/networkmanager/firewall-client.js
  pkg/networkmanager/firewall.jsx
  pkg/networkmanager/index.html
  pkg/networkmanager/networking.css
  test/selenium/selenium-firewalld-zones.py
  test/selenium/selenium-firewalld.py
  test/verify/check-networking-firewall
Labels: release-note

#12977 tests: Fedora testing does not support `Download an OS`
  test/verify/machineslib.py
Labels: no-test

#12945 storage: Fix layout of StorageLink:s in content tabs
  pkg/storaged/storage-controls.jsx
Labels: release-blocker

#12981 Update translations from Fedora Zanata
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/it.po
  po/ja.po
  po/ko.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#12962 "Autofocus" on "Verification Code / Conversation Input"
  src/ws/login.js
Labels: release-blocker

#12990 tls: handle gnutls error codes correctly
  src/tls/connection.c
Labels: release-blocker

#12991 base1: Fix race condition in building dist/base1/react-core-base.css
  src/base1/Makefile.am
Labels: no-test, release-blocker

#12985 branding: Cover login page with background image
  doc/branding.md
  src/branding/centos/branding.css
  src/branding/debian/branding.css
  src/branding/default/branding.css
  src/branding/fedora/branding.css
  src/branding/kubernetes/branding.css
  src/branding/registry/branding.css
  src/branding/rhel/branding.css
  src/branding/scientific/branding.css
  src/branding/ubuntu/branding.css
Labels: no-test

#12997 test: fix selenium test MachinesStoragePoolTestSuite.testCheckStorage…
  test/selenium/selenium-machines-storage-pool.py
Labels: no-test

#12995 tls: Fix some typos
  src/tls/connection.c
Labels: release-blocker

#13000 lib: remove unused css rule from listing.less
  pkg/lib/listing.less
Labels: no-test

#12998 package.json: Update react package dependency
  package.json
Labels: bot

#13004 tls: Increase timeout in HTTPS response test
  src/tls/test-server.c
Labels: no-test

#13008 systemd: Specify context for `After`
  pkg/systemd/services.html
Labels: no-test

#13012 tls: Fix comment on connection_handshake()
  src/tls/connection.c
Labels: no-test

#13017 test: Fix NTP tests on Ubuntu 19.10
  test/verify/check-system-info
Labels: no-test

#13018 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#13031 po: Fix update-po for separate build dir
  po/Makefile.am
Labels: no-test

#13035 package.json: Update react-dom package dependency
  package.json
Labels: bot

#13037 test: Fix selenium firewall tests
  test/selenium/selenium-firewalld.py
Labels: no-test, release-blocker

#13025 login: make default choice in login page the 'Reuse my password for p…
  src/ws/login.js
Labels: release-note

#13033 machines: Pass only active storage pools to the Add Disk dialog compo…
  pkg/machines/components/diskAdd.jsx
  pkg/machines/components/vmDisksTab.jsx
Labels: release-blocker

#13044 test: Skip FreeIPA tests on debian-testing
  test/verify/check-realms
Labels: no-test

#13049 test: Fix race condition in test15BaseSSHKeyAdded
  test/selenium/testlib_avocado/seleniumlib.py
Labels: no-test
