Repository cockpit-project/cockpit, pull requests merged in 2019-11, with the labels that each got.

#13068 Revert "test: Skip Machines selenium tests on Edge for now"
  test/selenium/run-tests
  test/selenium/selenium-machines-basic.py
  test/selenium/selenium-machines-storage-pool.py
Labels: no-test

#13081 Test po-refresh without old client
  po/cs.po
Labels: bot, no-test

#13083 package.json: Update bootstrap-select package dependency
  package.json
Labels: bot

#13027 subscriptions: Install insights-client on demand
  Makefile.am
  configure.ac
  pkg/subscriptions/index.html
  pkg/subscriptions/insights.jsx
  pkg/subscriptions/main.js
  pkg/subscriptions/manifest.json.in
  pkg/subscriptions/subscriptions-client.js
  pkg/subscriptions/subscriptions-register.jsx
  pkg/systemd/host.js
  test/verify/check-subscriptions
  tools/cockpit.spec
Labels: unrelated-test-failure

#13103 test: Use new services image instead of candlepin and ipa
  pkg/realmd/README.md
  test/verify/check-packagekit
  test/verify/check-realms
  test/verify/check-subscriptions
Labels: backport, unrelated-test-failure

#13104 test: Use new services image instead of candlepin and ipa
  pkg/realmd/README.md
  test/verify/check-packagekit
  test/verify/check-realms
Labels: backport

#13105 test: Use new services image instead of candlepin and ipa
  pkg/realmd/README.md
  test/verify/check-packagekit
  test/verify/check-realms
Labels: backport

#13096 shell: Label search input
  pkg/shell/index.html
Labels: no-test

#13107 test: Do not blur input after setting up text
  test/common/testlib.py
  test/verify/check-machines-dbus
Labels: unrelated-test-failure

#13106 package.json: Update patternfly-react package dependency
  package.json
Labels: bot

#13108 Do not use requirejs in example
  examples/ocserv/manifest.json
  examples/ocserv/ocserv.html
Labels: no-test

#13116 Update translations from Fedora Zanata
  po/cs.po
  po/pl.po
  po/uk.po
Labels: bot

#13119 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#13129 test: Use only fedora-23-stock in check-multi-os [rhel-8.1]
  test/README.md
  test/verify/check-multi-os
Labels: backport

#13130 test: Use only fedora-23-stock in check-multi-os [rhel-8-appstream]
  test/README.md
  test/verify/check-multi-os
Labels: backport

#13128 test: Use only fedora-23-stock in check-multi-os [rhel-7.8]
  test/README.md
  test/verify/check-multi-os
Labels: backport

#13136 playground: Don't rely on /etc/hostname
  pkg/playground/preloaded.js
Labels: unrelated-test-failure

#13134 selinux: Do not wrap text around button on small screens
  pkg/selinux/setroubleshoot-view.jsx
  pkg/selinux/setroubleshoot.css
Labels: no-test, release-blocker

#13140 machines: fix typo in CSS which broke ToastNotifications
  pkg/machines/machines.less
Labels: release-blocker, unrelated-test-failure

#13153 doc: Update cockpit/ws documentation
  doc/guide/authentication.xml
Labels: no-test

#13161 package.json: Update react-redux package dependency
  package.json
Labels: bot

#13150 package.json: Update react package dependency
  package.json
Labels: bot

#13159 Update translations from Fedora Zanata
  po/cs.po
  po/pl.po
  po/uk.po
Labels: bot

#11150 systemd: logs: Use reportd for reporting problems
  pkg/systemd/host.css
  pkg/systemd/logs.html
  pkg/systemd/logs.js
  pkg/systemd/reporting.jsx
  test/verify/check-docker
  test/verify/check-journal
  test/verify/files/mock-bugzilla-server.py
  test/verify/files/mock-faf-server.py
  tools/cockpit.spec
Labels: release-note

#13147 playground: PatternFly 4 Cards
  pkg/playground/react-demo-cards.jsx
  pkg/playground/react-patterns.html
  pkg/playground/react-patterns.js
Labels: no-test

#13177 package.json: Update react-dom package dependency
  package.json
Labels: bot

#13169 test: Add centos-8-stream
  test/README.md
  test/verify/check-docker
  test/verify/check-docker-storage
  test/verify/check-journal
  test/verify/check-kdump
  test/verify/check-packagekit
  test/verify/check-services
  test/verify/check-storage-format
  test/verify/check-storage-luks
  test/verify/check-storage-resize
  test/verify/check-system-info
  test/verify/machineslib.py
  test/verify/packagelib.py
Labels: no-test

#13180 storage: Fix duplicate mount point handling with encryption
  pkg/storaged/fsys-tab.jsx
  test/verify/check-storage-mounting
Labels: release-blocker

#13185 package.json: Update patternfly-react package dependency
  package.json
Labels: bot

#13187 Update translations from Fedora Zanata
  po/cs.po
  po/pl.po
  po/uk.po
Labels: bot

#13190 realm: Don't show error alert on an freshly open 'Join Domain' dialog
  pkg/realmd/operation.html
  pkg/realmd/operation.js
Labels: release-blocker

#13196 tools: Fix SELinux policy update hack in %post
  tools/cockpit.spec
Labels: release-blocker

#13191 test: Use selenium containers on services image
  test/selenium/README.md
  test/selenium/run-tests
Labels: no-test

#13205 [rhel-7.8] test: Use selenium containers on services image
  test/avocado/README.md
  test/avocado/run-tests
Labels: backport

#13204 [rhel-8-appstream] test: Use selenium containers on services image
  test/avocado/README.md
  test/avocado/run-tests
Labels: backport, unrelated-test-failure

#13203 [rhel-8.1] test: Use selenium containers on services image
  test/avocado/README.md
  test/avocado/run-tests
Labels: backport

#13211 package.json: Update deep-equal package dependency
  package.json
Labels: bot

#13208 spec: Remove cockpit-wsinstance-factory in specfile
  tools/cockpit.spec
Labels: no-test
