Repository cockpit-project/cockpit, pull requests merged in 2020-04, with the labels that each got.

#13828 test: Also cleanup selinux modules
  test/verify/check-setroubleshoot
Labels: unrelated-test-failure

#13829 test: Also reload libvirtd on debian-testing
  test/verify/check-machines-dbus
Labels: no-test

#13838 Revert "containers: Fix unit-tests container for SELinux"
  containers/unit-tests/README.md
  containers/unit-tests/run.sh
  containers/unit-tests/start
Labels: no-test

#13843 test: Restore utmp in check-login to pacify libvirt
  test/verify/check-login
Labels: no-test

#13846 Update translations from Fedora Weblate
  po/ca.po
  po/ru.po
  po/zh_TW.po
Labels: bot

#13842 Check for NPM dependency updates
  package.json
Labels: bot

#13847 shell: Remove unused #server css rules
  pkg/shell/shell.scss
Labels: no-test

#13849 test: Make check for no failed services more robust, take #2
  test/verify/check-services
Labels: unrelated-test-failure

#13851 test: Skip dhclient-modifying tests on Fedora CoreOS
  test/verify/check-networking-bond
  test/verify/check-networking-checkpoints
Labels: no-test

#13766 machines: Disable qemu:///session for Virtual Network creation
  pkg/machines/app.jsx
  pkg/machines/components/networks/createNetworkDialog.jsx
  pkg/machines/components/networks/networkList.jsx
Labels: unrelated-test-failure

#13858 test: Add expected message to TestMachines.testCreate
  test/verify/machineslib.py
Labels: no-test

#13859 selenium: Drop some Selenium machines tests covered by Fedora gating tests
  test/selenium/selenium-machines-consoles.py
  test/selenium/selenium-machines-network-page.py
  test/selenium/selenium-machines-networks.py
  test/selenium/selenium-machines-storage-pool.py
  test/selenium/selenium-machines-usage.py
  test/selenium/selenium-machines-vcpu.py
Labels: no-test

#13864 package.json: Update uuid package dependency
  package.json
Labels: bot

#13875 test: Stop cockpit.service quietly
  test/common/testlib.py
Labels: no-test

#13876 machines: Split DeleteResourceSource component to avoid nesting statefull modals inside table rows
  pkg/machines/components/deleteResource.jsx
  pkg/machines/components/networks/network.jsx
  pkg/machines/components/vmDisksTab.jsx
  pkg/machines/components/vmnetworktab.jsx
Labels: needswork

#13878 doc: Recommend FreeBind option when listening to specific IP
  doc/guide/listen.xml
Labels: no-test

#13890 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#13891 package.json: Update deep-equal package dependency
  package.json
Labels: bot

#13888 machines: Fix network device detection
  pkg/machines/components/vmnetworktab.jsx
Labels: unrelated-test-failure

#13897 apps: Use flex instead of table in caption
  pkg/apps/application-list.jsx
  pkg/apps/application.css
Labels: unrelated-test-failure

#13898 Change empty state secondary buttons to use link-styled buttons
  pkg/machines/components/libvirtSlate.jsx
  pkg/packagekit/updates.jsx
  test/verify/check-packagekit
  test/verify/machineslib.py
Labels: release-blocker

#13907 test: Fix Machines testNICAdd permanent attachment
  test/verify/check-machines-dbus
Labels: release-blocker, unrelated-test-failure

#13910 test: Drop chrony purging from debian-testing
  test/verify/check-system-info
Labels: no-test

#13908 tests: add some tips to README.md
  test/README.md
Labels: no-test

#13911 containers: Bump bastion and ws containers to Fedora 31
  containers/bastion/Dockerfile
  containers/ws/Dockerfile
Labels: no-test

#13919 overview: remove bottom margin under motd
  pkg/systemd/overview-cards/motdCard.scss
Labels: no-test

#13924 base1: Adjust test-http for recent playground change
  src/base1/test-http.js
Labels: no-test, release-blocker

#13925 Update translations from Fedora Weblate
  po/fr.po
  po/nl.po
  po/ru.po
  po/uk.po
Labels: bot

#13920 systemd: Add instructions how to test Active Directory
  pkg/systemd/README-realmd.md
Labels: no-test

#13923 package.json: Update bootstrap-select package dependency
  package.json
Labels: bot

#13903 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: blocked, bot

#13929 test: Ignore "invalid locale" messages on Debian
  test/common/testlib.py
Labels: no-test

#13930 test: Skip tangd-update.service hack on rhel-7-9
  test/verify/check-storage-luks
Labels: no-test

#13928 Adjust tests for rhel-8-3
  test/README.md
  test/verify/check-docker
  test/verify/check-journal
  test/verify/check-kdump
  test/verify/check-login
  test/verify/check-networking-firewall
  test/verify/check-packagekit
  test/verify/check-storage-format
  test/verify/check-storage-luks
  test/verify/check-storage-resize
  test/verify/check-system-info
  test/verify/machineslib.py
Labels: blocked, no-test

#13885 systemd: Display uptime on overview page
  pkg/systemd/overview-cards/systemInformationCard.jsx
  test/verify/check-system-info
Labels: release-note

#13931 shell: Disable idle timeout by default
  doc/man/cockpit.conf.xml
  pkg/shell/base_index.js
  test/verify/check-menu
Labels: release-note

#13934 ws: Accept upper-case login names for ssh/polkit agent challenges
  src/ws/cockpitwebservice.c
  test/verify/check-realms
Labels: release-blocker

#13977 pkg: Import polyfills on all pages that use finally()
  pkg/kdump/kdump.js
  pkg/machines/index.js
  pkg/packagekit/updates.jsx
  pkg/storaged/devices.jsx
  pkg/storaged/nfs-details.jsx
  pkg/systemd/hwinfo.jsx
  pkg/systemd/overview.jsx
  pkg/systemd/services/services.jsx
  pkg/users/local.js
Labels: release-blocker

#13967 ssh: Require libssh ≥ 0.8.5
  configure.ac
  src/ssh/Makefile-ssh.am
  src/ssh/cockpitsshknownhosts.c
  src/ssh/cockpitsshknownhosts.h
  src/ssh/cockpitsshrelay.c
  src/ssh/test-knownhosts.c
  src/ssh/test-sshbridge.c
  tools/cockpit.spec
  tools/debian/control
Labels: unrelated-test-failure

#13978 test: Drop ubuntu-1804 special cases
  test/README.md
  test/verify/check-docker
  test/verify/check-journal
  test/verify/check-kdump
  test/verify/check-login
  test/verify/check-machines-dbus
  test/verify/check-metrics
  test/verify/check-multi-machine
  test/verify/check-multi-machine-key
  test/verify/check-networking-bond
  test/verify/check-networking-checkpoints
  test/verify/check-networking-firewall
  test/verify/check-packagekit
  test/verify/check-realms
  test/verify/check-setroubleshoot
  test/verify/check-storage-iscsi
  test/verify/check-storage-luks
  test/verify/check-storage-multipath
  test/verify/check-storage-resize
  test/verify/machineslib.py
Labels: no-test

#13979 test: Skip tangd hack on centos-8
  test/verify/check-storage-luks
Labels: no-test

#13980 test: Don't fail on `Failed to generate stack trace: (null)`
  test/common/testlib.py
Labels: no-test

#13974 Update translations from Fedora Weblate
  po/cs.po
  po/es.po
  po/pl.po
Labels: bot

#13976 HACKING: Avoid bridge on the host when starting windows-10
  HACKING.md
Labels: documentation, no-test

#13988 test: Cleanup modules on ansible machine
  test/verify/check-setroubleshoot
Labels: release-blocker

#13989 doc: Clarify GSSAPI authentication
  doc/authentication.md
Labels: no-test, release-blocker

#13994 tools: Make unit tests non-fatal on Fedora s390x
  tools/cockpit.spec
Labels: no-test, release-blocker
