Repository cockpit-project/cockpit, pull requests merged in 2020-08, with the labels that each got.

#14432 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, release-blocker

#14433 Fix weight values for Redhat fonts
  src/base1/_fonts.scss
Labels: unrelated-test-failure

#14442 ws: Add key usage and constraints to self-signed server certificate
  src/ws/cockpitcertificate.c
  test/verify/check-connection
Labels: release-blocker, unrelated-test-failure

#14452 package.json: Update patternfly-react package dependency
  package.json
Labels: bot

#14458 Drop Travis config
  .travis.yml
Labels: no-test

#14457 test: Adjust special cases for ubuntu-stable moving to 20.10
  test/verify/check-docker
  test/verify/check-machines
  test/verify/check-metrics
  test/verify/check-networking-checkpoints
  test/verify/check-realms
  test/verify/check-system-info
Labels: blocked, no-test

#14464 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#14474 package.json: Update throttle-debounce package dependency
  package.json
Labels: bot

#14479 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#14470 storage: Support "noauto" crypto backing devices better
  pkg/storaged/format-dialog.jsx
  pkg/storaged/fsys-tab.jsx
  test/verify/check-storage-luks
  test/verify/check-storage-mounting
Labels: release-blocker, release-note, unrelated-test-failure

#14494 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#14499 package.json: Update qunit package dependency
  package.json
Labels: bot

#14500 Update translations from Fedora Weblate
  po/fr.po
  po/it.po
Labels: bot

#14504 cockpituous: Stop releasing to Fedora 31
  tools/cockpituous-release
Labels: no-test

#14525 test: Replace deprecated `time.clock()` with `time.process_time()`
  test/selenium/testlib_avocado/seleniumlib.py
Labels: no-test

#14529 [rhel-8.3] test: Replace deprecated `time.clock()` with `time.process_time()`
  test/selenium/testlib_avocado/seleniumlib.py
Labels: backport

#14526 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#14528 sosreport: Adjust to output format in sosreport 4.0
  pkg/sosreport/index.js
Labels: release-blocker

#14530 [rhel-7.9] test: Replace deprecated `time.clock()` with `time.process_time()`
  test/avocado/testlib_avocado/seleniumlib.py
Labels: backport

#14531 [rhel-7.9] ws: Use default krb5 enctypes from mock KDC
  src/ws/mock-kdc.conf.in
Labels: backport

#14535 networking: interface-details: stop using container-fluid bootstrap class for page layout
  pkg/networkmanager/index.html
  pkg/networkmanager/interfaces.js
  pkg/networkmanager/networking.css
Labels: release-blocker

#14536 Update translations from Fedora Weblate
  po/he.po
  po/zh_CN.po
Labels: bot
