Repository cockpit-project/cockpit, pull requests merged in 2020-06, with the labels that each got.

#14167 test: Fix FIPS mode enabling on RHEL
  test/verify/check-multi-machine
Labels: unrelated-test-failure

#14162 package.json: Update @patternfly/react-console package dependency
  package.json
Labels: bot

#14169 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: bot

#14172 [r82] test: Adjust Machines tests for test VMs with > 1 GiB RAM
  test/verify/machineslib.py
Labels: backport

#14177 test: Fake EOL date of Fedora 28
  test/verify/check-machines
Labels: release-blocker

#14179 ws: Stop setting G_TLS_GNUTLS_PRIORITY
  src/ws/main.c
Labels: release-blocker

#14180 Revert "tests: add a test case which is deleting the vm during its in…
  test/verify/check-machines
Labels: release-blocker

#14154 machines: fix setting of volume format when adding new disks to VMs
  pkg/machines/components/diskAdd.jsx
  pkg/machines/libvirt-virsh.js
  pkg/machines/xmlCreator.js
  test/verify/machineslib.py
Labels: backport

#14185 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#14184 all: Add { superuser: "try" } for things that might need Polkit
  pkg/lib/machines.js
  pkg/networkmanager/firewall-client.js
  pkg/realmd/operation.js
  pkg/selinux/setroubleshoot-client.js
Labels: backport

#14178 test: Add special cases for rhel-8-3-distropkg
  test/README.md
  test/common/testlib.py
  test/verify/check-docker
  test/verify/check-journal
  test/verify/check-kdump
  test/verify/check-login
  test/verify/check-machines
  test/verify/check-networking-firewall
  test/verify/check-storage-format
  test/verify/check-storage-luks
  test/verify/check-storage-resize
  test/verify/check-system-info
Labels: no-test

#14189 test/README.md: Refer to bots documentation for images
  test/README.md
Labels: no-test

#14190 test: Drop get_temp_dir() usage from image-prepare
  test/image-prepare
Labels: no-test

#14191 package.json: Update deep-equal package dependency
  package.json
Labels: bot

#14192 test: Fix preferences for new Firefox
  test/common/cdp.py
Labels: no-test

#14193 Drop unused imports-loader dependency
  package.json
Labels: unrelated-test-failure

#14208 test: allow networking in testlib's global machine
  test/common/run-tests
  test/common/testlib.py
Labels: release-blocker

#14211 test: Check overlaying cockpit-ws RPM on Fedora CoreOS
  test/common/testlib.py
  test/verify/check-connection
Labels: unrelated-test-failure

#14209 containers/ws: Document how to enable password SSH logins
  containers/ws/README.md
Labels: no-test, release-blocker

#14207 ws: Replace deprecated PermissionsStartOnly systemd option
  src/ws/cockpit.service.in
Labels: unrelated-test-failure

#14213 test: Skip problematic exception in Firefox
  test/common/firefox-cdp-driver.js
Labels: no-test

#14216 tools: Don't run slow unit tests on RISC-V architectures in Debian/Ubuntu
  tools/debian/rules
Labels: no-test, release-blocker

#14217 test/common/run-tests: don't fail when not run from a git checkout
  test/common/run-tests
Labels: release-blocker

#14205 package.json: Update bootstrap-select package dependency
  package.json
Labels: bot

#14218 Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/he.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, release-blocker

#14225 test: Fix run-tests to get along with non-blocking stdout
  test/common/run-tests
Labels: no-test

#14224 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: bot

#14230 base1: Ship base1/patternfly.css again
  src/base1/Makefile.am
Labels: no-test, release-blocker

#14228 guide: Drop obsolete "SSL Versions and Ciphers" section
  doc/guide/https.xml
Labels: documentation, no-test

#14237 tools: Don't run unit tests on RHEL 8 i686
  tools/cockpit.spec
Labels: no-test

#14238 run-tests: Don't try machines tests 3 times
  test/common/run-tests
Labels: release-blocker

#14242 test: Adjust SSH fingerprint parsing for RHEL 8.3 OpenSSH
  test/verify/check-multi-machine
Labels: unrelated-test-failure

#14243 test: Adjust to RHEL 8.3 getting cockpit 221.1
  test/verify/check-accounts
  test/verify/check-connection
  test/verify/check-host-switching
  test/verify/check-journal
  test/verify/check-networking-firewall
  test/verify/check-pages
  test/verify/check-realms
  test/verify/check-roles
  test/verify/check-setroubleshoot
  test/verify/check-system-info
Labels: blocked, no-test

#14245 test: Adjust for /etc/ssh/sshd_config.d/ directory
  test/verify/check-loopback
  test/verify/check-multi-machine-key
Labels: unrelated-test-failure

#14244 Update translations from Fedora Weblate
  po/de.po
  po/fr.po
  po/ru.po
  po/sv.po
Labels: bot, release-blocker

#14249 package.json: Update qunit package dependency
  package.json
Labels: bot

#14254 test: Enable TestIPA.testClientCertAuthentication on centos-8-stream
  test/verify/check-realms
Labels: no-test

#14257 package.json: Update remarkable package dependency
  package.json
Labels: bot

#14262 logs: Use predefined filters rather than 'start' option
  pkg/systemd/logs.html
  pkg/systemd/logs.js
  pkg/systemd/logs.scss
  test/selenium/selenium-navigate.py
  test/verify/check-journal
Labels: release-note

#14273 test: Increase timeout for terminal flooding test
  test/verify/check-terminal
Labels: release-blocker

#14271 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot
