Repository cockpit-project/cockpit, pull requests merged in 2020-09, with the labels that each got.

#14543 machines: fix distance between the chart elements in VM Usage tab
  pkg/machines/c3charts.jsx
  pkg/machines/components/vm/vmUsageTab.jsx
  test/verify/check-machines
Labels: release-blocker

#14561 package.json: Update @patternfly/react-table package dependency
  package.json
Labels: bot

#14566 kdump: Utilize description list instead of form for displaying data
  pkg/kdump/kdump-view.jsx
  pkg/lib/patternfly/patternfly-4-overrides.scss
Labels: unrelated-test-failure

#14557 users: Allow weak passwords
  pkg/users/account-create-dialog.js
  pkg/users/password-dialogs.js
  pkg/users/users.scss
  test/verify/check-accounts
Labels: release-note

#14576 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#14577 firewall: Fixup spacing in translation string
  pkg/networkmanager/index.html
Labels: no-test, unrelated-test-failure

#14594 machines: Fix shared proptype introduced in commit f5b0630
  pkg/machines/components/vnc.jsx
Labels: release-blocker

#14595 test: Ignore ip6tables crash on ubuntu-stable as well
  test/common/testlib.py
Labels: flake, no-test

#14607 Dear bots, would you mind doing a po-refresh? Danke!
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#14589 storage: Some Card layout and render fixes
  pkg/lib/ct-card.scss
  pkg/storaged/storage.scss
Labels: unrelated-test-failure

#14613 package.json: Update qunit package dependency
  package.json
Labels: bot

#14615 ssh: Fix parsing of IPv6 addresses
  src/ssh/cockpitsshrelay.c
  src/ssh/mock_known_hosts
  src/ssh/test-sshbridge.c
  test/verify/check-login
Labels: release-blocker

#14626 test: Fix race condition in TestLogin.testBasic
  test/verify/check-login
Labels: release-blocker

#14633 package.json: Update moment package dependency
  package.json
Labels: bot

#14628 Bump optimize-css-assets-webpack-plugin to latest version
  package.json
  webpack.config.js
Labels: unrelated-test-failure

#14636 Update translations from Fedora Weblate
  po/cs.po
  po/ja.po
  po/nl.po
  po/pl.po
  po/zh_CN.po
Labels: bot

#14642 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#14652 test: In check-metrics, check if image has swap
  test/verify/check-metrics
Labels: unrelated-test-failure

#14648 tools: Fix building without libssh-devel
  tools/cockpit.spec
Labels: release-blocker

#14643 package.json: Update @patternfly/react-table package dependency
  package.json
Labels: bot

#14661 test: Adapt TestMachines to fixed bug in fedora-33
  test/verify/check-machines
Labels: blocked, unrelated-test-failure

#14662 test: More cryptsetup PBKDF adjustments
  test/verify/check-storage-resize
  test/verify/check-storage-used
Labels: unrelated-test-failure

#14663 [rhel-8.3] test: More cryptsetup PBKDF adjustments
  test/verify/check-storage-resize
  test/verify/check-storage-used
Labels: backport

#14665 package.json: Update xterm package dependency
  package.json
Labels: bot

#14664 test: Introduce check with nightly dnf
  test/run
Labels: no-test

#14666 test: Increase timeout for fips-mode-setup
  test/verify/check-multi-machine
Labels: flake

#14674 test: Enable FreeIPA tests on ubuntu-2004
  test/verify/check-realms
Labels: no-test

#14675 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: bot, unrelated-test-failure

#14683 test: Quiesce Chromium logorhea
  test/common/cdp.py
Labels: no-test, release-blocker
