Repository cockpit-project/cockpit, pull requests merged in 2020-07, with the labels that each got.

#14288 test: Add check for nginx reverse proxy for plain-http cockpit
  test/verify/check-connection
Labels: unrelated-test-failure

#14270 package.json: Update xterm package dependency
  package.json
Labels: bot

#14295 package.json: Update patternfly package dependency
  package.json
Labels: bot

#14314 package.json: Update moment package dependency
  package.json
Labels: bot

#14311 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#14323 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#14329 Translations refresh
  po/cs.po
  po/de.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/uk.po
  po/zh_CN.po
Labels: bot, release-blocker

#14331 test: Adjust check-login for changed sshd config on Fedora CoreOS
  test/verify/check-login
Labels: no-test

#14334 package.json: Update @patternfly/react-table package dependency
  package.json
Labels: bot

#14348 package.json: Update throttle-debounce package dependency
  package.json
Labels: bot

#14352 test: Add test for historic PCP data
  test/verify/check-metrics
Labels: unrelated-test-failure

#14361 [rhel-7.9] package.json: Fix version for novnc
  package.json
Labels: backport

#14359 Update translations from Fedora Weblate
  po/fr.po
  po/it.po
  po/zh_CN.po
Labels: bot

#14365 tls: Fix expired test CA
  src/tls/ca/alice-expired.pem
  src/tls/ca/alice.key
  src/tls/ca/alice.p12
  src/tls/ca/alice.pem
  src/tls/ca/bob.key
  src/tls/ca/bob.p12
  src/tls/ca/bob.pem
  src/tls/ca/ca.key
  src/tls/ca/ca.pem
  src/tls/ca/generate.sh
  src/tls/testing.h
Labels: release-blocker

#14366 test: Fix TestMachines.testConfigureBeforeInstall on fedora-testing
  test/verify/check-machines
Labels: no-test

#14369 Drop vagrant support
  HACKING.md
  Vagrantfile
Labels: no-test

#14370 HACKING: Document how to build distribution packages
  HACKING.md
Labels: documentation, no-test

#14368 package.json: Update bootstrap-select package dependency
  package.json
Labels: bot

#14377 machines: fix close button on the header of NIC Edit modal dialog
  pkg/machines/components/nicEdit.jsx
Labels: release-blocker

#14372 session: reopen memfd ro to avoid SELinux trouble
  src/ws/session-utils.c
  src/ws/session-utils.h
  src/ws/session.c
  test/verify/check-login
Labels: release-blocker

#14380 containers/ws: Adjust install instructions for image download
  containers/ws/README.md
Labels: no-test

#14382 machines: add --wait -1 option to virt-install for all installation types
  pkg/machines/scripts/create_machine.sh
  test/verify/check-machines
Labels: release-blocker

#14383 lib: fix keyboard natigation in the NavItems of expandable table rows
  pkg/lib/cockpit-components-listing-panel.jsx
  pkg/machines/components/vm/vmExpandedContent.jsx
  pkg/storaged/content-views.jsx
Labels: release-blocker, unrelated-test-failure

#14397 test: Fix TestSOS.testCancel
  test/verify/check-sosreport
Labels: unrelated-test-failure

#14401 test: Drop selenium kdump test
  test/selenium/run-tests
  test/selenium/selenium-kdump.py
Labels: no-test

#14398 all: Adjust documentation URLs to recent RHEL docs changes
  pkg/machines/manifest.json.in
  pkg/networkmanager/manifest.json.in
  pkg/systemd/manifest.json.in
Labels: release-blocker, unrelated-test-failure

#14392 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/it.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/sv.po
  po/uk.po
  po/zh_TW.po
Labels: bot

#14404 test: Make sure that default libvirt network is defined in Machines tests
  test/verify/check-machines
Labels: unrelated-test-failure

#14407 machines: Fix TypeError for OSRow in VM creation dialog
  pkg/machines/components/create-vm-dialog/createVmDialog.jsx
Labels: release-blocker

#14413 package.json: Update qunit package dependency
  package.json
Labels: bot

#14417 machines: Fix progressbar alignment (mostly)
  pkg/machines/components/storagePools/storagePoolList.scss
Labels: unrelated-test-failure

#14259 machines: Implement creation of VM snapshots
  pkg/machines/components/vmSnapshotsCreateModal.jsx
  pkg/machines/components/vmSnapshotsTab.jsx
  pkg/machines/libvirt-dbus.js
  pkg/machines/xmlCreator.js
  test/verify/check-machines
  test/verify/machinesxmls.py
Labels: release-note

#14426 test: Adjust TestLogin.testSELinuxRestrictedUser on rhel-8-3-distropkg
  test/verify/check-login
Labels: no-test

#14429 package.json: Update xterm package dependency
  package.json
Labels: bot

#14431 ws: Clean up unsupported krb5 enctypes from mock KDC
  src/ws/mock-kdc.conf.in
Labels: release-blocker
