Repository cockpit-project/cockpit, pull requests merged in 2020-12, with the labels that each got.

#14986 workflows: Fix npm-update token
  .github/workflows/npm-update.yml
Labels: no-test

#14983 [r83] tests: Stop using CirrOS image - since 20/11/20 it's missing from the…
  pkg/machines/components/create-vm-dialog/createVmDialog.jsx
  test/verify/check-machines
Labels: backport

#14984 containers: Move unit-tests container to GitHub registry
  .github/workflows/unit-tests-refresh.yml
  containers/unit-tests/build
  containers/unit-tests/start
Labels: no-test

#14987 tools: Prevent co-installation of newer bridge with older cockpit-docker
  tools/cockpit.spec
  tools/debian/control
Labels: release-blocker

#14992 workflows: Fix npm-update
  .github/workflows/npm-update.yml
Labels: no-test, release-blocker

#14905 dashboard: So Long
  Makefile.am
  README.md
  containers/ws/install-package.sh
  doc/guide/cockpit-location.xml
  doc/guide/feature-machines.xml
  doc/guide/listen.xml
  doc/guide/packages.xml
  doc/guide/startup.xml
  doc/guide/urls.xml
  doc/setup.md
  pkg/dashboard/dashboard.scss
  pkg/dashboard/index.html
  pkg/dashboard/list.js
  pkg/dashboard/manifest.json.in
  pkg/shell/indexes.js
  pkg/users/users.scss
  src/ws/cockpit.appdata.xml.in
  test/common/testlib.py
  test/verify/check-connection
  test/verify/check-dashboard
  test/verify/check-host-switching
  test/verify/check-multi-machine
  test/verify/check-multi-machine-key
  test/verify/check-multi-os
  test/verify/check-packagekit
  test/verify/check-realms
  test/verify/check-superuser
  tools/cockpit.spec
  tools/debian/cockpit-dashboard.install
  tools/debian/control
  webpack.config.js
Labels: release-note

#14994 [no-test] Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#14995 test: centos-8-stream image supports VM firmware configuration now
  test/verify/check-machines
Labels: no-test

#14997 [r83] test: centos-8-stream image supports VM firmware configuration now
  test/verify/check-machines
Labels: backport

#14999 workflows: Update release container registry
  .github/workflows/release.yml
Labels: no-test

#15002 package.json: Update deep-equal package dependency
  package.json
Labels: bot

#15001 machines: Drop unnecessary aria-label
  pkg/machines/components/vmSnapshotsCreateModal.jsx
Labels: no-test

#14996 package.json: Update qunit package dependency
  package.json
Labels: bot

#14989 test: Use proper config for sos 4
  test/verify/check-sosreport
Labels: unrelated-test-failure

#14954 machines: add support for cloning VMs
  pkg/machines/components/vm/vmActions.jsx
  pkg/machines/components/vmCloneDialog.jsx
  pkg/machines/components/vmCloneDialog.scss
  test/verify/check-machines
Labels: release-note

#15011 package.json: Update mustache package dependency
  package.json
Labels: bot

#15012 workflows: Fix unit tests with podman
  .github/workflows/unit-tests.yml
Labels: no-test

#15013 workflows: Fix unit tests with podman for container refreshes
  .github/workflows/unit-tests-refresh.yml
Labels: no-test

#14977 tools: Build all binary packages for EPEL
  tools/cockpit.spec
Labels: release-blocker, unrelated-test-failure

#15020 [no-test] Update translations from Fedora Weblate
  po/nl.po
  po/tr.po
Labels: bot, no-test, release-blocker

#15036 workflows: Fix apt installation
  .github/workflows/npm-update.yml
  .github/workflows/po-refresh.yml
Labels: no-test

#15043 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#15037 overview: allow editing motd
  pkg/systemd/overview-cards/motdCard.jsx
  test/verify/check-system-info
Labels: release-note

#15052 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: bot

#15061 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#15065 tools: Clean up cockpit-ws system user creation
  tools/debian/cockpit-ws.postinst
Labels: unrelated-test-failure

#15075 workflows: Move npm-update to Ubuntu 20.04
  .github/workflows/npm-update.yml
Labels: no-test

#15076 [no-test] Update translations from Fedora Weblate
  po/nl.po
  po/pl.po
  po/sk.po
  po/tr.po
Labels: bot, no-test, release-blocker

#15078 [no-test] Update translations from Fedora Weblate
  po/sk.po
Labels: bot, no-test, release-blocker

#15072 containers: Bump bastion and ws containers to Fedora 33
  containers/bastion/Dockerfile
  containers/ws/Dockerfile
Labels: unrelated-test-failure
