Repository cockpit-project/cockpit, pull requests merged in 2020-03, with the labels that each got.

#13638 package.json: Update react-redux package dependency
  package.json
Labels: bot

#13634 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#13649 kdump: Apply width to the modal-dialog class instead of modal in kdump dialog
  pkg/kdump/kdump.scss
Labels: release-blocker

#13657 packagekit: Add stylesheet for the Buttons on 'Software Updates' page
  pkg/packagekit/updates.scss
Labels: release-blocker

#13665 test: Allow more sudo noise for SELinux restricted users
  test/verify/check-login
Labels: no-test

#13672 test: Robustify NM online hack for Ubuntu
  test/verify/packagelib.py
Labels: no-test

#13679 [7.8] Adjust to new version of eslint
  pkg/networkmanager/firewall.jsx
  pkg/systemd/hwinfo.jsx
Labels: backport

#13680 [8.2] Adjust to new version of eslint
  pkg/networkmanager/firewall.jsx
  pkg/systemd/hwinfo.jsx
Labels: backport

#13681 packagekit: Leave some space between "available" and "history" tables
  pkg/packagekit/updates.scss
Labels: no-test

#13664 package.json: Update @patternfly/react-table package dependency
  package.json
Labels: bot

#13692 Update translations from Fedora Weblate
  po/nl.po
Labels: bot

#13698 test: Fix TAP output for infrastructure retries in run-tests
  test/verify/run-tests
Labels: no-test

#13704 Drop cockpit-docker for Debian/Ubuntu development series, some packaging cleanups
  test/verify/check-docker
  tools/debian/control
  tools/debian/rules
Labels: no-test

#13708 tools: Fix RPM weak dependencies
  tools/cockpit.spec
Labels: backport

#13710 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: bot

#13719 tools: Set Debian's cockpit metapackage dependencies to same version
  tools/debian/control
Labels: no-test

#13686 firewall: Show ports that were directly added to the firewall
  pkg/networkmanager/firewall-client.js
  pkg/networkmanager/firewall.jsx
  pkg/networkmanager/networking.css
  test/verify/check-networking-firewall
Labels: release-note, unrelated-test-failure

#13723 test: Fix starting libvirt default network after restarting firewalld
  test/verify/check-networking-firewall
Labels: release-blocker

#13729 cockpituous: Disable releasing to COPR
  tools/cockpituous-release
Labels: no-test

#13730 [r78] machines: fix CPU statistics
  pkg/machines/components/vm/vmUsageTab.jsx
  pkg/machines/libvirt-virsh.js
Labels: backport

#13727 package.json: Update patternfly-react package dependency
  package.json
Labels: bot

#13735 build: Consistently use absolute source and build dir
  Makefile.am
Labels: release-blocker

#13739 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, release-blocker

#13740 test: Change `print_exc()` to `format_exc()`
  test/common/testlib.py
Labels: no-test

#13738 firewall: Use ids for services instead of names
  pkg/networkmanager/firewall.jsx
  test/verify/check-networking-firewall
Labels: release-blocker, release-note

#13732 test: Add another expected message to TestLogin.testSELinuxRestrictedUser
  test/verify/check-login
Labels: no-test

#13744 test: Fix cleanup in TestStorage.testLvm
  test/verify/check-storage-lvm2
Labels: no-test, release-blocker

#13745 test: Add expected AppArmor messages for TestMachines.testAddDisk on ubuntu-stable
  test/verify/machineslib.py
Labels: no-test, release-blocker

#13749 test: Robustify check-machines iSCSI tests
  test/verify/check-machines-dbus
  test/verify/machineslib.py
Labels: unrelated-test-failure

#13755 test: Compress journals
  test/common/testlib.py
Labels: no-test

#13759 build: Don't produce cockpit-cache.tar.gz in dist-gzip mode
  Makefile.am
Labels: no-test

#13762 tools: Include commit sha in rpm name
  configure.ac
  tools/git-version-gen
Labels: no-test

#13769 [rhel-8.2] test: Use centos-7 image instead of fedora-23-stock in check-multi-os
  test/README.md
  test/verify/check-multi-os
Labels: backport

#13770 [rhel-7.8] test: Use centos-7 image instead of fedora-23-stock in check-multi-os
  test/README.md
  test/verify/check-multi-os
Labels: backport

#13765 package.json: Update @patternfly/react-table package dependency
  package.json
Labels: bot

#13775 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: bot

#13772 test: Clarify selenium-machines-non-root.py
  test/selenium/selenium-machines-non-root.py
Labels: no-test

#13777 test: Allow some capacity wiggle room in check-storage-lvm2 testLvm
  test/verify/check-storage-lvm2
Labels: unrelated-test-failure

#13800 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#13803 systemd: Fix error message when joining AD domains
  pkg/systemd/overview-cards/realmd-operation.js
Labels: release-blocker

#13802 systemd: Fix showing the "More" diagnostics in realm join dialog
  pkg/systemd/overview-cards/realmd-operation.js
  test/verify/check-realms
Labels: release-blocker

#13813 containers: Add VERSION label to cockpit/ws
  containers/ws/Dockerfile
Labels: no-test

#13801 package.json: Update @patternfly/react-console package dependency
  package.json
Labels: bot

#13814 bridge: Pass connectable to TLS client connection
  src/bridge/cockpitconnect.c
Labels: release-blocker

#13817 Do not use fuzzy translations
  po/po2json
Labels: no-test, release-blocker

#13819 test: Make check for no failed services more robust
  test/verify/check-services
Labels: release-blocker

#13824 build: Unbreak git worktrees
  configure.ac
Labels: no-test
