Repository cockpit-project/cockpit, pull requests merged in 2020-05, with the labels that each got.

#14018 specfile: Fix up requires for cockpit-system
  tools/cockpit.spec
Labels: no-test

#14019 test: Allow authorize messages in check-login testBasic
  test/verify/check-login
Labels: no-test

#14017 doc: Use standard Promise API and ES6 arrow handlers
  doc/guide/cockpit-channel.xml
  doc/guide/cockpit-dbus.xml
  doc/guide/cockpit-file.xml
  doc/guide/cockpit-http.xml
  doc/guide/cockpit-session.xml
  doc/guide/cockpit-spawn.xml
Labels: no-test

#14014 examples: Modernize pinger
  examples/pinger/ping.html
  examples/pinger/pinger.js
Labels: no-test, unrelated-test-failure

#14005 package.json: Update @patternfly/react-table package dependency
  package.json
Labels: bot

#14024 test: Possibility to add allowed messages from ENV
  test/common/testlib.py
Labels: no-test

#14029 examples: Add missing doctype and <html> start tag to pinger
  examples/pinger/ping.html
Labels: no-test

#14025 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#14015 tests: Merge test files machines and address one test failure
  test/verify/check-machines
  test/verify/check-machines-dbus
  test/verify/machinesxmls.py
Labels: unrelated-test-failure

#14050 test: Split off non-destructive SMT tests to replace selenium test
  test/selenium/selenium-hwinfo.py
  test/verify/check-system-info
Labels: unrelated-test-failure

#14042 machines: remove workaround for PF3 slider component
  pkg/machines/components/memorySelectRow.jsx
Labels: release-blocker

#13972 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#14071 test: Fix chcon test
  test/verify/check-system-info
  test/verify/netlib.py
Labels: release-blocker

#14078 Update translations from Fedora Weblate
  pkg/shell/manifest.json.in
  po/LINGUAS
  po/he.po
Labels: bot

#14046 systemd: Don't use cockpit.permission for Services
  pkg/systemd/services/service.jsx
  pkg/systemd/services/services.jsx
Labels: release-blocker

#14079 common: Fix deadlock in channel pressure handling
  src/common/cockpitchannel.c
  test/verify/check-terminal
Labels: release-blocker

#14082 tools: Drop obsolete second release-dockerhub invocation
  tools/cockpituous-release
Labels: no-test, release-blocker

#14081 [rhel-8.2] test: Sync master selenium tests
  test/selenium/selenium-machines-storage-pool.py
Labels: backport, no-test

#14086 package.json: Update moment package dependency
  package.json
Labels: bot

#14090 test: Ignore qemu-kvm → /dev/mapper/control SELinux policy violation on rhel-8-3
  test/common/testlib.py
Labels: no-test

#14099 test: Add C unit test timeout
  Makefile.am
Labels: unrelated-test-failure

#14112 test: Adjust to changed clipboard permissions in current Chromium
  test/verify/check-setroubleshoot
  test/verify/check-terminal
Labels: unrelated-test-failure

#14116 Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot

#14120 tools: Revert cockpit-system → setroubleshoot-server dependency on RHEL
  tools/cockpit.spec
Labels: no-test, release-blocker

#14122 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#14130 test: Adjust to changed clipboard permissions in current Chromium
  test/verify/check-setroubleshoot
  test/verify/check-terminal
Labels: backport, unrelated-test-failure

#14138 test: Add --machine/--browser options to run-tests
  test/verify/check-testlib
  test/verify/run-tests
Labels: release-blocker

#14147 tools: Drop cockpit-dashboard recommendation from cockpit metapackage
  tools/cockpit.spec
  tools/debian/control
Labels: release-blocker

#14139 package.json: Update xterm package dependency
  package.json
Labels: bot

#14152 shell: Clicking connection error indicator oopses
  pkg/shell/base_index.js
Labels: unrelated-test-failure

#14155 test: Latest rhel-8-3 image supports VM firmware selection
  test/verify/check-machines
Labels: no-test

#14157 test: Move run-tests to test/common
  test/common/parent.py
  test/common/run-tests
  test/run
  test/verify/check-testlib
  test/verify/parent.py
Labels: release-blocker

#14158 test: Adjust Machines tests for test VMs with 1 GiB RAM
  test/verify/check-machines
Labels: release-blocker

#14055 shell: Make the super-user-indicator apply to the current machine
  pkg/shell/indexes.js
  pkg/shell/superuser.jsx
  test/verify/check-superuser
Labels: release-blocker

#14108 logs: Introduce inline help
  pkg/systemd/logs.html
  pkg/systemd/logs.js
  pkg/systemd/logs.scss
  test/verify/check-journal
Labels: release-blocker, release-note
