Repository cockpit-project/cockpit, pull requests merged in 2020-01, with the labels that each got.

#13344 Update translations from Fedora Zanata
  po/cs.po
  po/fr.po
  po/pl.po
  po/uk.po
Labels: bot

#13350 test: Avoid time going backwards in check-services timer test
  test/verify/check-services
Labels: release-blocker

#13353 test: Add expected testSELinuxRestrictedUser messages on centos-8-stream
  test/verify/check-login
Labels: no-test

#13342 package.json: Update @patternfly/react-console package dependency
  package.json
Labels: bot

#13305 systemd: Add CPU usage to Overview Usage card
  pkg/systemd/overview-cards/usageCard.jsx
  test/verify/check-metrics
Labels: release-note

#13358 package.json: Update react-bootstrap package dependency
  package.json
Labels: bot, unrelated-test-failure

#13209 machines: Support bus type configuration for disks
  pkg/machines/actions/provider-actions.js
  pkg/machines/components/diskAdd.jsx
  pkg/machines/components/diskEdit.jsx
  pkg/machines/components/vcpuModal.css
  pkg/machines/helpers.js
  pkg/machines/libvirt-common.js
  pkg/machines/libvirt-dbus.js
  pkg/machines/machines.less
  pkg/machines/xmlCreator.js
  test/verify/check-machines-dbus
  test/verify/machineslib.py
Labels: release-note

#13368 packagekit: Properly localize timestamps
  pkg/packagekit/updates.jsx
Labels: unrelated-test-failure

#13379 test: Update supported OSes in README
  test/README.md
Labels: no-test

#13382 package.json: Update redux package dependency
  package.json
Labels: bot

#13369 realmd: Don't directly manipulate the DOM
  Makefile.am
  pkg/lib/cockpit-components-privileged.jsx
  pkg/realmd/manifest.json.in
  pkg/systemd/README-realmd.md
  pkg/systemd/index.html
  pkg/systemd/overview-cards/configurationCard.jsx
  pkg/systemd/overview-cards/realmd-operation.html
  pkg/systemd/overview-cards/realmd-operation.js
  test/verify/check-realms
  tools/cockpit.spec
  tools/debian/cockpit-system.install
  tools/debian/control
Labels: release-blocker

#13389 HACKING: Document how to use locally built cockpit-ws
  HACKING.md
Labels: no-test

#13392 test: Add rhel-8-2-distropkg special cases
  test/README.md
  test/common/testlib.py
  test/verify/check-accounts
  test/verify/check-connection
  test/verify/check-docker
  test/verify/check-docker-storage
  test/verify/check-journal
  test/verify/check-kdump
  test/verify/check-realms
  test/verify/check-storage-format
  test/verify/check-storage-luks
  test/verify/check-storage-resize
  test/verify/check-system-info
Labels: no-test

#13390 common: Fix large requests with TLS
  src/common/cockpitwebserver.c
  src/common/cockpitwebserver.h
  src/common/test-webserver.c
  test/verify/check-connection
Labels: backport

#13407 docker: Always use variables in ngettext
  pkg/docker/containers-view.jsx
Labels: release-blocker

#13412 Translations refresh from Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/it.po
  po/ja.po
  po/ko.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sv.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, release-blocker

#13388 tls: Support separate certificate key file
  doc/guide/https.xml
  src/common/cockpitwebcertificate.c
  src/common/cockpitwebcertificate.h
  src/common/test-webcertificate.c
  src/tls/connection.c
  src/tls/connection.h
  src/tls/main.c
  src/tls/test-server.c
  src/ws/cockpitcertificate.c
  test/verify/check-connection
Labels: release-note

#13397 Graph page layout fixups
  pkg/systemd/graphs.less
Labels: release-blocker

#13424 tests: Check naughties also on third retry
  test/common/testlib.py
Labels: backport

#13426 machines: Fix broken translation
  pkg/machines/index.html
Labels: release-blocker

#13417 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: bot

#13427 systemd: Fix graphs having wrong `display` attribute
  pkg/systemd/graphs.js
Labels: release-blocker

#13425 graphs: Include PF4 components
  pkg/systemd/graphs.less
Labels: release-blocker

#13405 test: Add troubleshoot information to setroubleshoot failures
  test/verify/check-setroubleshoot
Labels: no-test

#13428 ws: Fix error message on missing browser APIs
  src/ws/login.js
Labels: release-blocker

#13429 Update translations from Fedora Weblate
  po/cs.po
  po/fr.po
  po/ja.po
  po/ko.po
  po/pl.po
  po/ru.po
  po/zh_CN.po
Labels: bot, release-blocker

#13408 machines: Fix default bridge selection for `Bridge to LAN` NIC
  pkg/machines/components/nicEdit.jsx
  test/verify/check-machines-dbus
Labels: release-blocker

#13432 overview: Don't allow the header to shrink
  pkg/systemd/overview.less
Labels: release-blocker

#13376 Show per page documentation
  doc/guide/packages.xml
  pkg/dashboard/manifest.json.in
  pkg/kdump/manifest.json.in
  pkg/machines/manifest.json.in
  pkg/networkmanager/manifest.json.in
  pkg/packagekit/manifest.json.in
  pkg/shell/base_index.js
  pkg/shell/index.html
  pkg/shell/indexes.js
  pkg/shell/shell.less
  pkg/storaged/manifest.json.in
  pkg/systemd/manifest.json.in
  pkg/users/manifest.json.in
  po/manifest2po
  src/common/cockpitsystem.c
  src/ws/cockpithandlers.c
  test/verify/check-pages
Labels: release-note

#13438 system: Fix graph layout across all browsers
  pkg/systemd/graphs.less
Labels: release-blocker

#13442 package.json: Update patternfly-react package dependency
  package.json
Labels: bot

#13458 .tasks: Drop learning trigger
  .tasks
Labels: no-test

#13460 testlib: Fix leaf_classes filter on module
  test/common/testlib.py
Labels: no-test

#13457 po: Pickup also strings with specified context
  po/Makefile.am
Labels: no-test

#13463 test: Update rhel-8-2-distropkg special cases for cockpit 211
  test/verify/check-login
  test/verify/check-packagekit
  test/verify/check-realms
  test/verify/check-reauthorize
  test/verify/check-shutdown-restart
Labels: blocked, no-test
