Repository cockpit-project/cockpit, pull requests merged in 2021-06, with the labels that each got.

#15879 test: Fix PackageCase NetworkManager setup
  test/verify/packagelib.py
Labels: release-blocker

#15881 [no-test] Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#15880 .github: Change node_modules approach
  .github/workflows/node_modules-publish.yml
  .github/workflows/node_modules-pull_request.yml
  .github/workflows/npm-install.yml
  .github/workflows/reposchutz.yml
  tools/README.node_modules
Labels: .github-changes

#15883 Fix missing borders in Selects
  webpack.config.js
Labels: release-blocker

#15897 reposchutz: drop superfluous check for tag
  .github/workflows/reposchutz.yml
Labels: .github-changes

#15892 livetest: stop spinning up a vm every single time anyone writes any comment on any PR or issue
  .github/workflows/livetest.yml
Labels: .github-changes

#15898 webpack: Remove workaround for redux
  webpack.config.js
Labels: no-test

#15905 lib: Update redirected links
  pkg/lib/cockpit-components-table.scss
  pkg/lib/patternfly/patternfly-4-overrides.scss
Labels: no-test

#15907 reposchutz: fix label-removing code
  .github/workflows/reposchutz.yml
Labels: .github-changes, no-test

#15915 [no-test] Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#15916 test: More robust pixel-tests pushing
  test/common/pixel-tests
Labels: no-test

#15940 workflows: Fix unit-tests' "changed" detection to compare against correct target branch
  .github/workflows/unit-tests.yml
Labels: .github-changes, no-test

#15970 configure.ac: Drop unused golang check
  configure.ac
Labels: no-test

#15971 webpack-watch: rework path handling a bit
  tools/webpack-watch
Labels: no-test

#15950 Revert "packit: add some fake docs as a temporary hack"
  packit.yaml
Labels: blocked, no-test

#15974 storage: Fix mounting of just created partitions
  pkg/storaged/format-dialog.jsx
  test/verify/check-storage-luks
  test/verify/check-storage-partitions
Labels: release-blocker

#15987 HACKING: Install official PAM config
  HACKING.md
Labels: no-test

#16006 various: replace 'master' with 'main' in urls
  containers/bastion/cockpit-auth-ssh-key
  doc/authentication.md
  doc/guide/authentication.xml
  doc/guide/cert-authentication.xml
  doc/guide/cockpit-http.xml
  doc/i18n.md
  pkg/metrics/metrics.jsx
  test/verify/check-metrics
  tools/cockpit.spec
Labels: release-blocker
