Repository cockpit-project/cockpit, pull requests merged in 2021-08, with the labels that each got.

#16185 shell: Change user icon in the top menu
  pkg/shell/index.html
  pkg/shell/nav.scss
Labels: release-note

#16190 test: Add IdentitiesOnly to the ssh config example
  test/README.md
Labels: no-test

#16193 [no-test] Update translations from Fedora Weblate
  po/ko.po
Labels: bot, no-test, release-blocker

#15871 storage: Use semantic HTML in verify key modal
  pkg/storaged/crypto-keyslots.jsx
  pkg/storaged/storage.scss
Labels: accessibility, enhancement, release-blocker

#16198 Generalize ignoring test output files
  .gitignore
Labels: no-test

#16206 doc: Document paths in cockpit.file
  doc/guide/cockpit-file.xml
Labels: no-test

#16210 test: fedora-testing does not have kpatch
  test/verify/check-packagekit
Labels: no-test

#16225 tools: Update user-agent in urls-check script
  tools/urls-check
Labels: no-test

#16220 bridge: Fix PCP archives on 32 bit architectures
  src/bridge/cockpitpcpmetrics.c
  src/bridge/test-pcp-archives.c
Labels: release-blocker

#16239 [no-test] Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: release-blocker, no-test, bot

#16254 [no-test] Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: release-blocker, no-test, bot

#16253 lib: Update PF link
  pkg/lib/cockpit-components-table.scss
Labels: no-test

#16274 cockpituous: Stop releasing to Fedora 33
  tools/cockpituous-release
Labels: no-test

#16273 webpack-watch: update webpack-make invocation
  HACKING.md
  tools/webpack-watch
Labels: no-test

#16272 [r85] po: Adjust weblate branch name to 8.5 branch
  po/Makefile.am
Labels: backport, no-test

#16222 shell: Use PF's about modal
  pkg/shell/images/bg-plain.jpg
  pkg/shell/images/cockpit-icon.svg
  pkg/shell/indexes.js
  pkg/shell/shell-modals.jsx
  test/verify/check-shell-menu
  webpack.config.js
Labels: release-note

#16284 test: Allow another variant of pcp-archive messages
  test/common/testlib.py
Labels: no-test
