Repository cockpit-project/cockpit, pull requests merged in 2021-04, with the labels that each got.

#15628 Offer and validate raid names
  pkg/storaged/mdraids-panel.jsx
  pkg/storaged/utils.js
  test/verify/check-storage-mdraid
Labels: unrelated-test-failure

#15647 test: Work around Firefox CDP mis-handling promise rejections
  test/common/firefox-cdp-driver.js
Labels: no-test

#15632 package.json: Update @patternfly/react-table, @patternfly/patternfly, @patternfly/react-styles, @patternfly/react-core
  package.json
Labels: bot

#15659 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#15658 [84] test: Centos-8-stream now has tracer
  test/verify/check-packagekit
Labels: backport

#15663 package.json: Update @patternfly/react-table, @patternfly/react-core
  package.json
Labels: bot

#15648 bridge: Allow '@' characters in package file paths
  src/bridge/cockpitpackages.c
  src/bridge/mock-resource/system/cockpit/test-priority/_modules/@testorg/toolkit.js
  src/bridge/test-packages.c
  src/ws/test-channelresponse.c
  src/ws/test-handlers.c
Labels: release-note

#15676 fmf: Don't install npm
  test/verify.fmf
Labels: no-test

#15684 [no-test] Update translations from Fedora Weblate
  po/ko.po
Labels: bot, no-test, release-blocker

#15685 networkmanager: Fix device connection button
  pkg/networkmanager/network-interface.jsx
  test/verify/check-networkmanager-basic
Labels: release-blocker

#15695 package.json: Update qunit
  package.json
Labels: bot

#15702 Drop obsolete "Atomic" references
  containers/ws/README.md
  doc/guide/feature-sosreport.xml
  test/verify/check-connection
  test/verify/check-static-login
Labels: no-test

#15705 [r84] test: Enable TLS for mock insights server
  test/verify/check-system-info
  test/verify/files/mock-insights
Labels: backport

#15706 test: Fix comment for mock-insights setup
  test/verify/check-system-info
Labels: no-test

#15708 tests: remove sit() from storage test
  test/verify/check-storage-format
Labels: no-test

#15718 workflows: Reduce published dist tarball retention to 3 days
  .github/workflows/publish-dist.yml
Labels: no-test

#15728 ws: Enable sandbox in cockpit-desktop's webkit browser
  src/ws/cockpit-desktop.in
Labels: no-test

#15733 workflows: Run unit-tests container as root
  .github/workflows/build-dist.yml
  .github/workflows/unit-tests.yml
Labels: no-test

#15744 Update link to Apache license
  pkg/base1/test-utf8.js
  tools/debian/copyright.template
Labels: no-test

#15754 [no-test] Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#15763 test: Fix initial expected memory in TestServices.testBasic
  test/verify/check-system-services
Labels: flake
