Repository cockpit-project/cockpit, pull requests merged in 2021-09, with the labels that each got.

#16286 [no-test] Update translations from Fedora Weblate
  po/fi.po
  po/it.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/tr.po
  po/uk.po
Labels: release-blocker, no-test, bot

#16289 test: Drop waiting for team MAC address
  test/verify/check-networkmanager-team
Labels: release-blocker

#16291 test: Relax expected "instance name lookup failed" PCP message
  test/common/testlib.py
Labels: release-blocker

#16288 test: Drop libvirt startup in check-networkmanager-firewall
  test/verify.fmf
  test/verify/check-networkmanager-firewall
Labels: release-blocker

#16259 test: Make TestUpdates.testBasic more robust
  test/verify/check-packagekit
Labels: release-blocker

#16296 workflows: Tag node-cache on releases
  .github/workflows/release.yml
Labels: no-test, .github-changes

#16298 [r85] containers: Fix SELinux context of SSH private key
  containers/bastion/README.md
  test/containers/check-bastion
Labels: backport

#16292 make webpack-watch a symlink of webpack-make
  tools/webpack-make
  tools/webpack-watch
Labels: no-test

#16305 containers/unit-tests: Add missing ddebs for security updates
  containers/unit-tests/setup.sh
Labels: no-test

#16312 tools: Provide eslint mode for webpack-watch
  HACKING.md
  tools/webpack-make
Labels: no-test

#16306 test: Port pixeldiff.html from jQuery to standard DOM API
  test/common/pixeldiff.html
Labels: no-test

#16314 [rhel-9.0] po: Update from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: blocked

#16326 [rhel-8.5] Update translations from Fedora Weblate
  po/ca.po
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: release-blocker, no-test, bot

#16331 [rhel-9.0] backport FMF hacks
  test/run-verify-host.sh
Labels: backport

#16341 pkg: Fix usage of `ngettext`
  pkg/networkmanager/network-main.jsx
  pkg/selinux/setroubleshoot-view.jsx
Labels: release-blocker

#16350 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: release-blocker, no-test, bot

#16351 test: Ignore cockpit-session chown SELinux failure on fedora-35
  test/verify/check-static-login
Labels: release-blocker, no-test

#16348 bridge: Robust JSON object comparison in test-httpstream.c
  src/bridge/test-httpstream.c
Labels: release-blocker

#16365 branding: Add Arch Linux branding
  Makefile.am
  src/branding/arch/Makefile.am
  src/branding/arch/branding.css
Labels: no-test, release-note

#16364 systemd: Use patternfly variables for spacing
  pkg/systemd/overview-cards/healthCard.scss
Labels: needs-rebase

#16367 test: Fix race in TestStorageMounting.testEncryptedMountingHelp harder
  test/verify/check-storage-mounting
Labels: flake

#16342 common: Restrict frame embedding to same origin
  doc/guide/embedding.xml
  pkg/base1/test-http.js
  src/bridge/test-httpstream.c
  src/bridge/test-packages.c
  src/common/cockpitwebresponse.c
  src/common/test-webresponse.c
  src/ws/test-channelresponse.c
  test/verify/check-connection
  test/verify/check-embed
Labels: release-note

#16373 [r79] test: Make expected exception a bit more general
  test/verify/check-menu
Labels: backport

#16377 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: release-blocker, no-test, bot

#16260 Move last login to system `Health` card
  pkg/systemd/overview-cards/healthCard.jsx
  pkg/systemd/overview-cards/lastLogin.jsx
  pkg/systemd/overview-cards/lastLogin.scss
  pkg/systemd/overview.jsx
  pkg/systemd/overview.scss
  test/verify/check-static-login
Labels: release-note, page:overview

#16388 metrics: Make WebKit happy with absolute position
  pkg/metrics/metrics.scss
Labels: release-blocker, page:metrics

#16393 test: Fix TestShutdownRestart.testBasic for different OS timezones
  test/verify/check-system-shutdown-restart
Labels: flake

#16409 systemd: Set auto-detected realm domain/admin as proper input values
  pkg/systemd/overview-cards/realmd-operation.html
  pkg/systemd/overview-cards/realmd-operation.js
  test/verify/check-system-realms
Labels: release-blocker

#16414 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: release-blocker, no-test, bot

#16416 bridge: Tone down ENODEV message about reading cgroups
  src/bridge/cockpitcgroupsamples.c
Labels: flake

#16411 po-refresh.yml: split out pot upload to weblate
  .github/workflows/po-refresh.yml
  po/Makefile.am
Labels: no-test, .github-changes

#16402 users: Add an list of recent logins to the account details
  pkg/systemd/overview-cards/lastLogin.jsx
  pkg/users/account-details.js
  pkg/users/account-logs-panel.jsx
  test/verify/check-users
Labels: release-blocker, release-note
