Repository cockpit-project/cockpit, pull requests merged in 2021-02, with the labels that each got.

#15253 tests: Fix git help spewage when running from releases
  test/common/run-tests
Labels: no-test, release-blocker

#15254 tools: Drop cockpit-appstream split for RHEL/ELN ≥ 9
  tools/cockpit.spec
  tools/make-srpm
Labels: release-blocker

#15258 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#15260 [no-test] Update translations from Fedora Weblate
  po/fi.po
  po/sk.po
  po/tr.po
Labels: bot, no-test, release-blocker

#15263 lib: workaround missing dataLabel property in <Th> PF4 component
  pkg/lib/cockpit-components-table.jsx
Labels: release-blocker

#15271 package.json: Update @patternfly/react-core, @patternfly/react-console
  package.json
Labels: bot

#15225 web_socket_util_parse_headers: Move Insert after check
  src/websocket/test-websocket.c
  src/websocket/websocket.c
Labels: release-blocker, release-note

#15280 packagekit: stretch page wrapper to fill screen vertically
  pkg/packagekit/updates.scss
Labels: release-blocker

#15281 tools: Rename Fedora rawhide branch in cockpituous control file
  tools/cockpituous-release
Labels: no-test, release-blocker

#15277 Add a global CSS rule for extending pages height and avoid double scrollbar
  pkg/apps/application.css
  pkg/apps/index.html
  pkg/kdump/index.html
  pkg/kdump/kdump-view.jsx
  pkg/lib/page.scss
  pkg/lib/patternfly/patternfly-overrides.scss
  pkg/lib/table.css
  pkg/machines/index.html
  pkg/metrics/index.html
  pkg/metrics/metrics.scss
  pkg/networkmanager/firewall.html
  pkg/networkmanager/index.html
  pkg/networkmanager/networking.scss
  pkg/packagekit/index.html
  pkg/packagekit/updates.scss
  pkg/selinux/setroubleshoot.html
  pkg/shell/shell.scss
  pkg/sosreport/index.html
  pkg/sosreport/sosreport.scss
  pkg/storaged/index.html
  pkg/systemd/hwinfo.html
  pkg/systemd/index.html
  pkg/systemd/logs.html
  pkg/systemd/logs.scss
  pkg/systemd/overview.scss
  pkg/systemd/services.html
  pkg/systemd/services/services.scss
  pkg/systemd/terminal.html
  pkg/systemd/terminal.scss
  pkg/users/index.html
Labels: no-test

#15285 firewall: Change order of aattributes to make tests happy
  pkg/networkmanager/firewall.html
Labels: release-blocker

#15287 test: Work around selenium Edge driver bug (change service version)
  test/selenium/selenium-base.py
Labels: no-test

#15290 cockpituous: Add Fedora 34 koji builds
  tools/cockpituous-release
Labels: no-test

#15294 Build `make dist` artifact for every master commit and PR
  .github/workflows/build-dist.yml
  Makefile.am
  containers/unit-tests/scenario-dist.sh
  containers/unit-tests/scenario-distcheck.sh
  containers/unit-tests/start
Labels: no-test

#15305 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#15297 Make sure that cockpit.language is set also when that is english
  pkg/base1/cockpit.js
Labels: release-blocker

#15306 workflows: Fix build-dist tarball name for PRs
  .github/workflows/build-dist.yml
Labels: no-test

#13525 machines: Disks with custom file paths
  pkg/machines/actions/provider-actions.js
  pkg/machines/components/vm/disks/diskAdd.jsx
  pkg/machines/libvirt-dbus.js
  pkg/machines/xmlCreator.js
  test/verify/check-machines-disks
Labels: release-note

#15323 test: FIx TestLogin.testTally for debian-testing
  test/verify/check-static-login
Labels: no-test

#15311 Replace 'restart' with 'reboot' when related to a system reboot
  doc/guide/feature-systemd.xml
  pkg/machines/components/vm/vmActions.jsx
  pkg/shell/indexes.js
  pkg/systemd/overview.jsx
  pkg/systemd/shutdown.jsx
  test/verify/check-pages
  test/verify/check-system-realms
  test/verify/check-system-shutdown-restart
Labels: release-blocker

#15330 package.json: Update @patternfly/react-core, @patternfly/react-console
  package.json
  pkg/machines/components/create-vm-dialog/createVmDialog.jsx
  test/verify/check-machines-create
Labels: bot

#15345 logs: Fix unclosed div as a result of dde47795
  pkg/systemd/logs.html
Labels: release-blocker

#15354 [no-test] Update translations from Fedora Weblate
  po/fi.po
  po/it.po
Labels: bot, no-test, release-blocker

#15357 test: Run cleanup handlers if debug artifact generation fails
  test/common/testlib.py
Labels: flake, release-blocker

#15347 machines: Refactor VMAddDiskDialog and fix testAddDiskCustomPath flake
  pkg/machines/components/vm/disks/diskAdd.jsx
  test/verify/check-machines-disks
Labels: release-blocker

#15355 package.json: Update @patternfly/react-core, @patternfly/react-styles, @patternfly/react-console, @patternfly/patternfly, @patternfly/react-table
  package.json
Labels: bot

#15346 machines: correct few details in storage page when pool's deactivated
  pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
  pkg/machines/components/storagePools/storageVolumeCreate.jsx
  test/verify/check-machines-storage-pools
Labels: needswork

#15373 Test tracer on rhel-8-4
  test/verify/check-packagekit
Labels: release-blocker

#15377 tools: Stop shipping unit tests
  tools/webpack-make
Labels: release-blocker

#15369 package.json: Update @patternfly/patternfly, @patternfly/react-core, @patternfly/react-styles, @patternfly/react-console, @patternfly/react-table
  package.json
Labels: bot

#15371 metrics: Don't show duplicate events
  pkg/metrics/metrics.jsx
  test/verify/check-metrics
  test/verify/files/metrics-archives/double_events.zip
Labels: release-blocker

#15386 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#15402 cockpituous: bodhi for Fedora 34, drop Fedora 32
  tools/cockpituous-release
Labels: no-test

#15401 lib: Check installed Red Hat products instead of yum config file
  pkg/lib/packagekit.js
Labels: release-blocker

#15404 services: rewrite create timer dialog to react
  pkg/lib/patternfly/patternfly-4-overrides.scss
  pkg/machines/machines.scss
  pkg/systemd/services.html
  pkg/systemd/services/services.jsx
  pkg/systemd/services/timer-dialog-helpers.js
  pkg/systemd/services/timer-dialog.js
  pkg/systemd/services/timer-dialog.jsx
  pkg/systemd/services/timers.scss
  test/verify/check-system-services
Labels: flake

#15410 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#15408 branding: Remove Debian favicon
  src/branding/debian/Makefile.am
  src/branding/debian/favicon.ico
Labels: no-test

#15413 test: Fix retry reason printing in run-tests
  test/common/run-tests
Labels: release-blocker

#15426 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#15428 test: Fix run-tests changed_pkgs crash for non-cockpit projects
  test/common/run-tests
Labels: release-blocker

#15437 HACKING.md: Document dbus-daemon as required unit test dependency
  HACKING.md
Labels: no-test
