Repository cockpit-project/cockpit, pull requests merged in 2021-11, with the labels that each got.

#16567 test: Don't restart NM while deleting devices at the same time
  test/verify/netlib.py
Labels: flake

#16573 base1: tweak error message check in test-dbus.js
  pkg/base1/test-dbus.js
Labels: no-test

#16592 fmf: Fix TEST_OS mappings
  test/run-verify-host-user.sh
Labels: no-test

#16599 test: Fix SELinux message matching
  test/verify/check-static-login
Labels: no-test

#16600 test: Use add_loopback_disk() to create loopback disks
  test/verify/check-storage-partitions
  test/verify/storagelib.py
Labels: flake

#16603 tests: fedora-coreos is now based on fedora-35 - adjust conditions accordingly
  test/verify/check-pages
Labels: blocked, no-test

#16604 login: Add toggle button to view password
  pkg/static/login.css
  pkg/static/login.html
  pkg/static/login.js
Labels: page:login

#16609 networkmanager: Update firewall documentation URL
  pkg/networkmanager/manifest.json
Labels: no-test

#16332 packit: Enable CentOS Stream 9
  packit.yaml
Labels: no-test

#16631 static: re-enable autologin if hostname was given
  pkg/static/login.js
Labels: release-blocker

#16642 cockpit-client: fix assertion in cockpit-client-ssh
  src/client/cockpit-client-ssh
Labels: release-blocker, no-test

#16643 cockpit-client: disable and hide forward/back
  src/client/cockpit-client
  src/client/cockpit-client.ui
Labels: no-test

#16647 cockpit-client: add a reload button
  src/client/cockpit-client
  src/client/cockpit-client.ui
Labels: no-test

#16646 flatpak: add screenshots to cockpit-client metainfo
  containers/flatpak/cockpit-client.metainfo.xml.in
Labels: no-test

#16654 tools: unset git envvars in git-utils.sh
  tools/git-utils.sh
Labels: no-test

#16656 client: remove all mentions of --wildly-insecure
  src/client/cockpit-client
Labels: no-test

#16657 workflows: use merge instead of head for flatpak test
  .github/workflows/flatpak-test.yml
Labels: no-test, .github-changes

#16658 flatpak: tweak our manifest to match downstream
  containers/flatpak/cockpit-client.yml.in
Labels: no-test
