Repository cockpit-project/cockpit, pull requests merged in 2021-01, with the labels that each got.

#15093 package.json: Update @patternfly/react-table package dependency
  package.json
Labels: bot

#15092 test: Fix firefox in visible mode
  test/common/cdp.py
Labels: no-test

#15094 session: add a bug reference to a comment
  src/ws/session-utils.c
Labels: documentation, no-test

#15098 [no-test] Update translations from Fedora Weblate
  po/fr.po
  po/sk.po
  po/uk.po
Labels: bot, no-test, release-blocker

#15103 tests: Add special cases for rhel-8-4-distropkg
  test/README.md
  test/verify/check-accounts
  test/verify/check-active-pages
  test/verify/check-bots-api
  test/verify/check-connection
  test/verify/check-embed
  test/verify/check-example
  test/verify/check-examples
  test/verify/check-host-switching
  test/verify/check-journal
  test/verify/check-kdump
  test/verify/check-keys
  test/verify/check-login
  test/verify/check-loopback
  test/verify/check-machines
  test/verify/check-menu
  test/verify/check-metrics
  test/verify/check-multi-machine
  test/verify/check-multi-machine-key
  test/verify/check-multi-os
  test/verify/check-networking-basic
  test/verify/check-networking-bond
  test/verify/check-networking-bridge
  test/verify/check-networking-checkpoints
  test/verify/check-networking-firewall
  test/verify/check-networking-mac
  test/verify/check-networking-mtu
  test/verify/check-networking-other
  test/verify/check-networking-settings
  test/verify/check-networking-team
  test/verify/check-networking-unmanaged
  test/verify/check-networking-vlan
  test/verify/check-pages
  test/verify/check-realms
  test/verify/check-reauthorize
  test/verify/check-roles
  test/verify/check-s4u-ssh
  test/verify/check-services
  test/verify/check-session
  test/verify/check-setroubleshoot
  test/verify/check-shutdown-restart
  test/verify/check-sosreport
  test/verify/check-storage-format
  test/verify/check-storage-luks
  test/verify/check-storage-resize
  test/verify/check-superuser
  test/verify/check-system-info
  test/verify/check-terminal
  test/verify/check-testlib
  test/verify/check-tuned
Labels: no-test

#15104 test: Dynamically detect swap in check-metrics
  test/verify/check-metrics
Labels: unrelated-test-failure

#15109 webpack: Quiesce sassc version
  webpack.config.js
Labels: no-test

#15136 test: Wait until link for .vv file is visible
  test/verify/check-machines
Labels: release-blocker

#15141 package.json: Update qunit package dependency
  package.json
Labels: bot

#15143 po: Don't double cd when building cockpit.appstream.pot
  po/Makefile.am
Labels: no-test

#15150 package.json: Update @patternfly/react-console package dependency
  package.json
Labels: bot

#15131 bridge: Only gather info from the first channel for peer bridges
  src/bridge/cockpitpeer.c
Labels: unrelated-test-failure

#15159 package.json: Update @patternfly/react-console package dependency
  package.json
Labels: bot

#15152 Reorganize check-metrics, fix "current memory" metric flake
  test/verify/check-metrics
Labels: flake, unrelated-test-failure

#15162 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#15163 Fix check-metrics tests that use prepareArchive()
  test/verify/check-metrics
Labels: flake, unrelated-test-failure

#15166 lib: Fix cockpit-po-plugin instantiation without options
  pkg/lib/cockpit-po-plugin.js
Labels: release-blocker

#15169 [rhel-8.3] test: Fix TestLogin.testExpired for pam_pwquality with retry=1
  test/verify/check-login
Labels: backport

#15176 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: bot, no-test, release-blocker

#15179 package.json: Lock @patternfly/react-styles version
  package.json
Labels: no-test, release-blocker

#15180 networking: Fix closing of "Connection lost" dialog
  pkg/networkmanager/interfaces.js
  test/verify/check-networking-checkpoints
Labels: release-blocker

#15175 lib/page: Improve color contrast for list errors
  pkg/lib/cockpit-components-table.scss
  pkg/lib/page.scss
  pkg/systemd/services/services.scss
Labels: release-blocker

#15186 Fix TestSystemInfo.testCPUSecurityMitigationsDetect flake
  test/verify/check-system-info
Labels: flake

#15215 package.json: Update @patternfly/react-styles package dependency
  package.json
Labels: bot

#15221 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pl.po
  po/ru.po
  po/sk.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
Labels: bot, no-test, release-blocker

#15222 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#15218 test: Restart packagekit service after we do cleanup
  test/verify/check-packagekit
  test/verify/packagelib.py
Labels: unrelated-test-failure

#15231 package.json: Update @patternfly/react-console package dependency
  package.json
Labels: bot

#15232 test: Enable screenshots for Firefox
  test/common/testlib.py
Labels: no-test

#15238 README.md: remove link to semaphore build status
  README.md
Labels: no-test

#15243 test: Fix check-realms curl invocation harder
  test/verify/check-realms
Labels: release-blocker

#15241 package.json: Update @patternfly/react-table, @patternfly/react-styles, @patternfly/react-core, @patternfly/patternfly
  package.json
Labels: bot

#15250 [rhel-7.9] test: fix an m.execute() invocation in check-realms
  test/verify/check-realms
Labels: backport, unrelated-test-failure

#15251 package.json: Update xterm
  package.json
Labels: bot
