Repository cockpit-project/cockpit, pull requests merged in 2022-03, with the labels that each got.

#17065 test: Ignore "ext2 filesystem" label in TestStorageBasic pixel test
  test/verify/check-storage-basic
Labels: flake, no-test

#16686 metrics: Show top CPU core usage
  pkg/metrics/metrics.jsx
  pkg/metrics/metrics.scss
  test/verify/check-metrics
Labels: release-note

#17073 pf: Add xs to flex gap override
  pkg/lib/patternfly/patternfly-4-overrides.scss
Labels: backport-to-9.0

#17072 test: Minimize scope of "seq" in firefox-cdp-driver.js
  test/common/firefox-cdp-driver.js
Labels: backport-to-9.0

#17039 metrics: Fix link construction for user services
  pkg/metrics/metrics.jsx
  test/verify/check-metrics
Labels: backport-to-9.0

#17081 test: Kill admin sessions after nondestructive tests
  test/common/testlib.py
Labels: flake

#17091 test: Increase timeout for load to drop
  test/verify/check-metrics
Labels: flake

#17099 packit.yaml: reduce the srpm depends
  packit.yaml
Labels: no-test

#17102 fmf: Drop cockpit packages from test dependencies
  test/verify.fmf
Labels: no-test

#17108 test: Drop rhel-8-5 from documented supported OSes
  test/README.md
Labels: documentation

#17110 test: Stop hardcoded Arch repository/mirror
  test/image-prepare
Labels: no-test

#17112 test/run: remove unused variable
  test/run
Labels: no-test

#17128 test: Robustify TestReauthorize.testSudo
  test/verify/check-reauthorize
Labels: flake

#17119 doc: Clarify unit of cockpit.file's max_read_size option
  doc/guide/cockpit-file.xml
Labels: no-test

#17141 tools/release-guide: adjust to build system changes
  tools/release-guide
Labels: release-blocker, no-test

#17145 shell: Re-include cross-package translations
  pkg/shell/index.html
Labels: release-blocker

#17152 tests: Stronger user/home directory cleanup between nondestructive tests
  test/common/testlib.py
Labels: flake

#17147 po: Translate messages from our extension AppStream metadata
  .github/workflows/flatpak-test.yml
  .gitignore
  containers/unit-tests/scenario/distcheck
  lgtm.yml
  pkg/Makefile.am
  pkg/kdump/org.cockpit-project.cockpit-kdump.metainfo.xml.in
  pkg/selinux/org.cockpit-project.cockpit-selinux.metainfo.xml.in
  pkg/sosreport/org.cockpit-project.cockpit-sosreport.metainfo.xml.in
  pkg/storaged/org.cockpit-project.cockpit-storaged.metainfo.xml.in
  po/Makefile.am
  tools/cockpit.spec.in
  tools/debian/control
Labels: .github-changes

#17151 test: test Arch Linux offline
  test/image-prepare
Labels: no-test

#17165 metrics: fix missing aria-label on progress element
  pkg/metrics/metrics.jsx
Labels: no-test

#17174 test: Enable FreeIPA tests on debian-testing
  test/verify/check-system-realms
Labels: blocked, no-test

#17183 containers: Update flatpak to GNOME runtime version 42
  containers/flatpak/cockpit-client.yml.in
Labels: no-test

#17198 .github: drop livetest.yml
  .github/workflows/livetest.yml
Labels: no-test, .github-changes

#17197 test: Enable 2FA auth tests on Debian/Ubuntu
  test/verify/check-system-realms
Labels: no-test

#17200 test: add firefox-developer to firefox binaries
  test/common/cdp.py
Labels: no-test
