Repository cockpit-project/cockpit, pull requests merged in 2022-01, with the labels that each got.

#16767 test: Relax expected memory plateau in TestPages.testPlots
  test/verify/check-pages
Labels: flake, no-test

#16769 test: Fix TestIPA.testUnqualifiedUsers 2FA race condition
  test/verify/check-system-realms
Labels: flake

#16771 urls-check: Ignore patternfly redirects
  tools/urls-check
Labels: no-test

#16751 Add a cockpit rsync webpack plugin for cockpit plugins
  pkg/lib/cockpit-rsync-plugin.js
  tools/webpack-make
Labels: no-test

#16776 shell: Fix locale provided to DatePicker
  pkg/lib/cockpit-components-shutdown.jsx
  pkg/lib/serverTime.js
  pkg/lib/timeformat.js
  pkg/systemd/services/timer-dialog.jsx
  pkg/users/expiration-dialogs.js
Labels: release-blocker

#16782 bridge: give hints for missing cockpit-system package
  src/bridge/cockpitpackages.c
Labels: release-blocker

#16784 flatpak: stop suggesting to install cockpit-bridge
  containers/flatpak/cockpit-client.metainfo.xml.in
Labels: release-blocker, no-test

#16786 tools: Fix comment for config.h check
  tools/test-static-code
Labels: no-test

#16785 flatpak workflow: validate the generated metainfo
  .github/workflows/flatpak-test.yml
Labels: no-test, .github-changes

#16795 test: Ignore unexpected certificate message in TestIPA.testQualifiedUsers
  test/verify/check-system-realms
Labels: flake

#16800 test: Allow more variations of "Unknown metric name" messages
  test/common/testlib.py
Labels: flake, no-test

#16807 common: Fix unused assignment in test_memfd_json_error_cases()
  src/common/test-jsonfds.c
Labels: no-test

#16809 test: sudo and socketpair() now work properly on fedora-testing
  test/verify/check-static-login
Labels: no-test

#16822 test: sudo and socketpair() now work properly on fedora-34
  test/verify/check-static-login
Labels: no-test

#16821 Fix TestConnection.testCockpitDesktop arch test, and race condition
  test/verify/check-connection
Labels: flake

#16832 test: Ignore realmd disconnect message on idle timeout for property updates
  test/verify/check-system-realms
Labels: flake

#16837 flatpak: Wait for application to stop during test
  containers/flatpak/test/test-ssh
Labels: flake, no-test

#16842 .gitignore: ignore *.log and *.trs
  .gitignore
Labels: no-test

#16849 [rhel-8.5] test: Don't expect only one item on dashboard
  test/verify/check-metrics
Labels: backport

#16852 [r8.5] test: sudo with cert auth now works on RHEL 8.6/C8S
  test/verify/check-system-realms
  test/verify/check-system-s4u
Labels: backport

#16854 git-hook-post-commit: deal with deleted files
  test/git-hook-post-commit
Labels: no-test

#16861 branding: fix symlink installation
  src/branding/arch/Makefile.am
  src/branding/centos/Makefile.am
  src/branding/debian/Makefile.am
  src/branding/fedora/Makefile.am
  src/branding/opensuse/Makefile.am
  src/branding/rhel/Makefile.am
  src/branding/scientific/Makefile.am
  src/branding/ubuntu/Makefile.am
Labels: release-blocker

#16848 test: sudo and socketpair() now work properly on fedora-35
  test/verify/check-static-login
Labels: blocked, release-blocker, no-test

#16859 build: Fix copy&paste typo in configure.ac's --enable-cockpit-client
  configure.ac
Labels: no-test

#16864 test: Adjust expected Fedora documentation name for fedora-testing
  test/verify/check-pages
Labels: no-test

#16872 Revert "build: add -ffile-prefix-map to CFLAGS"
  configure.ac
  containers/unit-tests/scenario/distcheck
Labels: release-blocker

#16875 packit: Run package build and unit tests on i386 and s390x
  packit.yaml
Labels: no-test

#16878 test: Give starting kdump.service more time in TestKDumpNFS
  test/verify/check-kdump
Labels: flake

#16870 build selinux policy as part of main build
  .gitignore
  Makefile.am
  configure.ac
  selinux/Makefile.am
  tools/cockpit.spec.in
Labels: no-test

#16888 Fixed incorrect memory information on multi-channel memory platforms.
  pkg/lib/machine-info.js
  test/verify/check-system-info
Labels: page:hwinfo

#16899 lib: Let webpack rsync plugin rsync to /usr/local/share/cockpit/
  pkg/lib/cockpit-rsync-plugin.js
Labels: no-test
