Repository cockpit-project/cockpit, pull requests merged in 2022-07, with the labels that each got.

#17494 test: document more testlib functions
  test/common/testlib.py
Labels: no-test

#17506 containers/ws: Support all OpenSSH key types
  containers/ws/README.md
  containers/ws/cockpit-auth-ssh-key
  containers/ws/label-run
  test/verify/check-ws-bastion
Labels: no-test, release-note

#17546 shell: update PF link to link to it's redirect
  pkg/shell/nav.scss
Labels: no-test

#17547 fmf: Fix syntax error in node_modules checkout
  test/browser/run-test.sh
Labels: no-test

#17160 Metrics: Add CPU temperature to metrics page
  pkg/metrics/metrics.jsx
  pkg/metrics/metrics.scss
  src/bridge/cockpitcpusamples.c
  src/bridge/cockpitcpusamples.h
  src/bridge/cockpitinternalmetrics.c
  src/bridge/test-metrics.c
  test/verify/check-metrics
Labels: release-note

#17553 client: Fix crash on absent Handy.StyleManager
  src/client/cockpit-client
Labels: release-blocker

#17500 packagekit: Add "Reboot after completion" switch to update progress page
  pkg/packagekit/updates.jsx
  pkg/packagekit/updates.scss
  test/verify/check-packagekit
Labels: release-note

#17559 test: Robustify testPackageKitCrash expected messages
  test/verify/check-packagekit
Labels: flake

#17564 ws: Fix test-channelresponse for glib dropping global child watch
  src/ws/test-channelresponse.c
Labels: release-blocker

#17570 workflows: Add build-ws-container
  .github/workflows/build-ws-container.yml
Labels: no-test, .github-changes

#17571 sosreport: Use "-v" instead of "-vvv" for verbose logging
  pkg/sosreport/index.jsx
  test/verify/check-sosreport
Labels: release-blocker

#17543 .github: always try to jumpstart node_modules
  .github/workflows/unit-tests.yml
Labels: no-test, .github-changes

#17583 packit: Drop obsolete FMF plan bumping
  packit.yaml
Labels: no-test
