Repository cockpit-project/cockpit, pull requests merged in 2022-12, with the labels that each got.

#17951 Update a list of distros which don't support realmd auto-detection
  test/verify/check-system-realms
Labels: blocked

#17983 doc: Fix factor default in cockpit.format_*()
  doc/guide/cockpit-util.xml
Labels: no-test

#17993 run-tests: using typing.List[] instead of list[]
  test/common/run-tests
Labels: release-blocker

#18004 test: Adjust testSELinuxRestrictedUser for fixed SELinux in RHEL 9.2
  test/verify/check-static-login
Labels: blocked, no-test

#18013 .github: run protection checks on Ubuntu 20.04
  .github/workflows/reposchutz.yml
Labels: no-test, .github-changes

#17988 selinux: avoid AT_SECURE on exec from cockpit-session
  selinux/cockpit.te
Labels: blocked

#18029 users: fix display of the groups view
  pkg/users/accounts-list.js
Labels: release-blocker

#18043 python: better exception handling in Transport code
  src/cockpit/transports.py
Labels: no-test

#18048 tools: Use GitHub API in debian/watch
  tools/debian/watch
Labels: no-test

#18063 lib: table: keys can be '0' which is falsy but still a valid key
  pkg/lib/cockpit-components-table.jsx
Labels: release-blocker

#18065 users: when the accounts list is empty because of filtering show the empty state in the table
  pkg/users/accounts-list.js
Labels: release-blocker
