Repository cockpit-project/cockpit, pull requests merged in 2022-10, with the labels that each got.

#17783 packit: Drop targets list from COPR build
  packit.yaml
Labels: no-test

#17786 gitleaks: Ignore mock SSH keys
  .gitleaks.toml
Labels: no-test

#17703 ci(lint): Add Shell linter - Differential Shellcheck
  .github/workflows/differential-shellcheck.yml
Labels: no-test, .github-changes

#17782 python: add CGroups v1 support
  src/cockpit/samples.py
Labels: no-test

#17781 fmf: Add lvm2 test dependency
  test/browser/main.fmf
Labels: release-blocker, no-test

#17807 doc: firewalld-cmd no longer exists
  doc/guide/feature-firewall.xml
Labels: no-test

#17803 python: add options control command
  src/cockpit/channel.py
Labels: no-test

#17847 test: Relax test skip expected output
  test/verify/check-testlib
Labels: release-blocker

#17846 flatpak: Use GNOME 43 runtime
  containers/flatpak/cockpit-client.yml.in
Labels: no-test

#17848 test: allowed systemd user journal corruption messages
  test/browser/run-test.sh
Labels: no-test

#17842 .github: update webpack-jumpstart actions
  .github/workflows/webpack-jumpstart.yml
Labels: no-test
