Repository cockpit-project/cockpit, pull requests merged in 2023-09, with the labels that each got.

#19265 test: Increase TestSELinux VM memory
  test/verify/check-selinux
Labels: flake

#19266 apps: Fix application progress bar
  pkg/apps/application-list.jsx
  pkg/apps/application.scss
Labels: release-blocker

#19280 test: include an Fedora updates-testing scenario
  test/run
Labels: no-test

#19289 test: Add VM's XML and VM's log into link-patterns
  test/common/link-patterns.json
Labels: no-test

#19291 tools: Fix "only arch all" Debian build
  tools/debian/rules
Labels: release-blocker, no-test

#19296 test: Explicitly trigger udev after resizing ext4
  test/verify/check-storage-resize
Labels: flake

#19298 .github: add nightly testing scenario
  .github/workflows/nightly.yml
Labels: no-test, .github-changes

#19301 Fix nightly runs
  .github/workflows/nightly.yml
Labels: no-test, .github-changes

#19306 tools: Explicitly set admin group on arch
  tools/arch/PKGBUILD
Labels: no-test

#19312 test: Fix TestMultiCPU.testCPUUsage for different scheduling
  test/verify/check-metrics
Labels: flake

#19314 test: Ignore help icon in bond dialog
  test/verify/check-networkmanager-bond
Labels: no-test

#19341 test: Clean up failed units in TestConnection.testUnitLifecycle
  test/verify/check-connection
Labels: flake

#19336 test: More general retrying for Storage content tabs
  test/common/storagelib.py
  test/common/testlib.py
Labels: flake

#19321 cockpit: add to_json() method to BridgeConfig
  src/cockpit/bridge.py
  test/verify/check-connection
Labels: release-blocker

#19339 Metrics: Link to network interface
  pkg/metrics/metrics.jsx
  test/verify/check-metrics
Labels: release-note

#19351 test: add avc type=1405
  test/common/testlib.py
Labels: release-blocker

#19377 doc: Drop wrong cockpit.user.onchanged()
  doc/guide/cockpit-session.xml
Labels: no-test

#19383 fmf: Fix installation of cockpit-tests
  test/browser/browser.sh
  test/browser/main.fmf
Labels: no-test

#18266 shell: python: load translations via manifest.js
  pkg/lib/cockpit-po-plugin.js
  pkg/shell/index.html
  src/cockpit/packages.py
  test/pytest/test_packages.py
Labels: pybridge

#19416 apps: Fix crash with nonexisting /etc/os-release
  pkg/apps/application-list.jsx
  test/verify/check-apps
Labels: release-blocker
