Repository cockpit-project/cockpit, pull requests merged in 2023-03, with the labels that each got.

#18442 test: Increase timeout for first Cockpit login
  test/common/testlib.py
Labels: flake

#18444 test: rhel4edge insights-client improvements
  test/verify/check-system-info
Labels: unrelated-test-failure

#18456 hacking: Wrapped URLs in `<>` to make them linkable on the website
  HACKING.md
Labels: no-test

#18469 test: Post fewer coverage comments
  test/common/lcov.py
Labels: no-test

#18473 test: Install dnf-automatic into TMT images
  test/browser/main.fmf
Labels: no-test

#18298 lib: Support custom time servers with chronyd
  pkg/lib/get-timesync-backend.py
  pkg/lib/serverTime.js
  test/verify/check-system-info
Labels: release-note

#18479 doc: drop host option from our documentation
  doc/guide/cockpit-channel.xml
  doc/guide/cockpit-dbus.xml
  doc/guide/cockpit-file.xml
  doc/guide/cockpit-spawn.xml
Labels: no-test

#18492 pkg: Support more than one target in window.debugging
  HACKING.md
  pkg/lib/cockpit-components-firewalld-request.jsx
  pkg/lib/cockpit-dark-theme.js
  pkg/lib/cockpit.js
  pkg/metrics/metrics.jsx
  pkg/packagekit/autoupdates.jsx
Labels: no-test

#18505 base1: Drop cockpit.dbus.publish() and .meta()
  doc/guide/cockpit-dbus.xml
  pkg/base1/test-dbus-common.js
  pkg/base1/test-dbus.js
  pkg/lib/cockpit.js
Labels: release-note

#18509 hacking: Improve used language
  HACKING.md
Labels: no-test

#18534 pkg: Update dist/ install rule to avoid `find` in dependencies
  pkg/Makefile.am
Labels: no-test

#18526 workflows: Avoid pkg/build in weblate-sync-pot.yml
  .github/workflows/weblate-sync-pot.yml
  po/Makefile.am
Labels: no-test, .github-changes

#18539 Update documentation and comments to not be webpack specific
  HACKING.md
  Makefile.am
  build.js
  pkg/Makefile.am
  pkg/lib/README
  pkg/lib/patternfly/patternfly-4-cockpit.scss
  src/cockpit/packages.py
  test/README.md
  tools/README.dist
  tools/build-debian-copyright
  tools/debian/copyright.template
  tools/debian/source/lintian-overrides
  tools/node-modules
Labels: no-test

#18353 Allow specifying UID during account creation
  pkg/users/account-create-dialog.js
  pkg/users/accounts-list.js
  pkg/users/users.js
  test/verify/check-users
Labels: release-note

#18508 lib: port the current manual NTP server dialog to PF
  pkg/lib/serverTime.js
  pkg/lib/serverTime.scss
  test/verify/check-system-info
Labels: release-blocker

#18491 shell/scss: Fix dark theme code background for new ssh host modal
  pkg/shell/hosts_dialog.jsx
  pkg/shell/shell.scss
Labels: flake

#18551 selinux: Fix menu entry
  pkg/selinux/manifest.json
Labels: release-blocker, no-test

#18555 lib/cockpit-rsync-plugin: Fix return value on failures
  pkg/lib/cockpit-rsync-plugin.js
Labels: no-test

#18562 tests: add rhel-8-9 special cases
  test/verify/check-connection
  test/verify/check-metrics
  test/verify/check-system-info
  test/verify/check-system-services
Labels: no-test

#18545 Hacking steps
  HACKING.md
Labels: no-test

#18234 users: Allow specifying home directory and shell during account creation
  pkg/users/account-create-dialog.js
  test/verify/check-users
Labels: release-note

#18565 build.js: Drop obsolete --config option
  build.js
Labels: no-test

#18579 various: replace mentions of IRC with Matrix
  HACKING.md
  README.md
Labels: blocked, no-test

#18586 pyproject.toml: enable pytest --strict-markers
  pyproject.toml
Labels: no-test

#18558 tests: update selector to match grafana from the new services image
  test/verify/check-metrics
Labels: no-test
