Repository cockpit-project/cockpit, pull requests merged in 2023-07, with the labels that each got.

#19048 test: Let "pixel-tests fetch" iterate over all scenarios
  test/common/pixel-tests
Labels: no-test

#19058 test: don't run testMultipleBridgeConfig in networking scenario
  test/run
Labels: no-test

#18915 common: handle non-blocking fd in cockpit_socket_receive_fd()
  src/common/cockpitfdpassing.c
  test/verify/check-superuser
Labels: release-blocker

#19092 tools: Adjust Debian libblockdev-mdraid dependency for udisks 2.10
  tools/debian/control
Labels: release-blocker, no-test

#19009 tools: Enable Python bridge on Fedora 38
  test/verify/check-client
  tools/cockpit.spec
Labels: release-blocker, no-test, pybridge

#19098 tools: Suggest mdadm for cockpit-storaged
  tools/debian/control
Labels: release-blocker, no-test

#19105 containers: Document showing the "RUN" label command
  containers/ws/README.md
Labels: no-test

#19136 pybridge: Asynchronously send package files in chunks
  src/cockpit/channels/packages.py
Labels: release-blocker, flake, bug, pybridge

#19144 flatpak: Update description
  src/client/org.cockpit_project.CockpitClient.metainfo.xml
Labels: no-test

#19147 pybridge: Fix crash when connecting to nonexisting D-Bus address
  pkg/base1/test-dbus.js
  src/cockpit/channels/dbus.py
Labels: release-blocker, pybridge

#19089 tools: don't parse --force as valid SHA
  tools/node-modules
Labels: no-test
