Repository cockpit-project/cockpit, pull requests merged in 2024-04, with the labels that each got.

#20236 shell, tuned: Update remaining doc links to RHEL 9
  pkg/shell/manifest.json
  pkg/systemd/overview-cards/tuned-dialog.jsx
Labels: no-test

#20251 Move remaining quay.io/cockpit/tasks references to ghcr.io
  .github/workflows/tasks-container-update.yml
  HACKING.md
  test/README.md
Labels: no-test, .github-changes

#20252 tools: add 'release' script
  .github/workflows/release.yml
  tools/release
Labels: .github-changes

#20265 lib: Add optional external open state to KebabDropdown
  pkg/lib/cockpit-components-dropdown.jsx
Labels: no-test

#20268 test: Fix login page flake in TestUpdates.testTracer
  test/verify/check-packagekit
Labels: flake

#20276 workflows: Run tasks-container-update in "self" environment
  .github/workflows/tasks-container-update.yml
Labels: no-test, .github-changes

#20286 workflows: Run release on Ubuntu 20.04
  .github/workflows/release.yml
Labels: release-blocker, no-test, .github-changes

#20295 dependabot: Group react packages
  .github/dependabot.yml
Labels: no-test, .github-changes

#20297 test: lcov: add coverage for ts/x files
  test/common/lcov.py
Labels: no-test

#20299 base1: add cockpit.assert()
  pkg/lib/cockpit.d.ts
  pkg/lib/cockpit.js
Labels: no-test

#20306 lib: the channel superuser option takes "try" or "require"
  pkg/lib/cockpit.d.ts
Labels: no-test

#20210 pytest: Bring back Transport tests
  test/pytest/test_transport.py
Labels: no-test, pybridge

#20316 lib: type all format related functions
  pkg/lib/cockpit.d.ts
Labels: no-test

#20323 bridge: fix a `(a and b) or c` case
  src/cockpit/channels/filesystem.py
Labels: no-test

#20328 test: Less aggressive pmlogger log cleaning in TestGrafanaClient
  test/verify/check-metrics
Labels: no-test

#20307 Extend cockpit typing
  pkg/lib/cockpit.d.ts
Labels: no-test

#20308 Type cockpit spawn
  files.js
  pkg/base1/test-promise.ts
  pkg/lib/cockpit.d.ts
Labels: no-test

#20348 test/static-code: speed up JSON validation
  test/static-code
Labels: no-test

#20329 storage: Exclude eMMC "boot" non-partitions from multipath logic
  pkg/storaged/client.js
Labels: release-blocker

#20366 test/README.md: document TEST_BIND_GLOBAL=1
  test/README.md
Labels: no-test

#20363 HACKING: add information on how to use React Developer Tools
  HACKING.md
Labels: no-test

#20345 lib: allow awaiting Dialogs.show()
  pkg/lib/dialogs.jsx
Labels: release-blocker

#20370 test: Fix unexpected "truncated data in external channel" messages
  test/common/testlib.py
  test/verify/check-superuser
  test/verify/check-system-terminal
Labels: flake
