Repository cockpit-project/cockpit, pull requests merged in 2024-06, with the labels that each got.

#20545 cockpit.js: make access to Gid field conditional
  pkg/lib/cockpit.js
Labels: release-blocker

#20548 fmf: Drop NetworkManager-team test dependency
  test/browser/browser.sh
  test/browser/main.fmf
Labels: release-blocker, no-test

#20544 tools: Drop i686 build on CentOS/RHEL 9 as well
  tools/cockpit.spec
Labels: release-blocker, no-test

#20556 lib: Fix ShutdownModal error type on `shutdown` errors
  pkg/lib/cockpit-components-shutdown.jsx
Labels: release-blocker

#20558 test: Bump PCP config dialog timeout
  test/verify/check-metrics
Labels: flake, no-test

#20560 test: tuned 2.23 fixes
  test/verify/check-system-tuned
Labels: release-blocker

#20572 packagekit: mention kpatch/updates in the manifest
  pkg/packagekit/manifest.json
Labels: no-test

#20583 test/static-code: make mypy deps configurable
  test/mypy-deps
  test/static-code
Labels: no-test

#20601 test: Stop failing on SELinux messages in rawhide and CentOS 10
  test/run
Labels: no-test

#20618 debian: Enable DynamicUser for cockpit-ws
  tools/debian/cockpit-ws.postinst
  tools/debian/control
  tools/debian/tests/control
  tools/debian/tests/smoke
Labels: release-blocker

#20620 tools: URLError has no attribute code
  tools/urls-check
Labels: no-test

#20630 [r8] test: Drop Grafana selector class names
  test/verify/check-metrics
Labels: backport

#20637 plans: add cockpit-files reverse dependency testing
  plans/files.fmf
Labels: no-test

#20651 tools: Disable cockpit-pcp on Fedora 39 on i686
  tools/cockpit.spec
Labels: release-blocker, no-test

#20627 tools: Update README.node_modules
  tools/README.node_modules.md
Labels: no-test

#20661 test: Adjust to kdump-utils split in Fedora 40
  test/vm.updates-testing
Labels: no-test

#20663 test: Tolerate absent /home
  test/common/testlib.py
Labels: no-test

#20665 test: Fix type of MachineCase.machine_class
  test/common/testlib.py
Labels: no-test

#20631 test: packagelib - check state before systemctl disable operations
  test/common/packagelib.py
Labels: no-test

#20664 test: don't type check pkg/lib outside of cockpit
  test/static-code
Labels: no-test

#20672 Revert "test: packagelib - robustify disabling of services"
  test/common/packagelib.py
Labels: flake, no-test

#20675 cockpit.d.ts: fix some `cockpit.file()` annotations
  pkg/lib/cockpit.d.ts
Labels: no-test
