Repository cockpit-project/cockpit, pull requests merged in 2024-01, with the labels that each got.

#19805 test: Wait until #account-locked gets initialized
  test/verify/check-users
Labels: flake

#19813 test: Robustify scheduled reboot check in TestAutoUpdates.testWithAvailableUpdates
  test/verify/check-packagekit
Labels: flake

#19835 test: workaround an old (and very common) flake
  test/verify/check-reauthorize
Labels: flake

#19826 storage: Support for creating biosboot and efi partitions
  doc/anaconda.md
  pkg/storaged/block/format-dialog.jsx
  test/verify/check-storage-anaconda
Labels: unrelated-test-failure

#19853 storage: Robustify btrfs polling
  pkg/storaged/client.js
Labels: release-blocker

#19843 storage: Allow creation of swap and maintain fstab entries
  pkg/storaged/block/format-dialog.jsx
  pkg/storaged/block/resize.jsx
  pkg/storaged/swap/swap.jsx
  pkg/storaged/utils.js
  test/verify/check-storage-swap
Labels: release-note

#19883 storage: pass configured swap partition in the cockpit_mount_points
  pkg/storaged/client.js
Labels: unrelated-test-failure

#19900 fsinfo channel: tweak a couple of options
  doc/protocol.md
  src/cockpit/channels/filesystem.py
  test/pytest/test_bridge.py
Labels: release-blocker

#19872 storaged: btrfs: allow btrfs subvolumes to be deleted
  pkg/storaged/btrfs/subvolume.jsx
  pkg/storaged/dialog.jsx
  test/verify/check-storage-btrfs
Labels: release-blocker, release-note

#19889 ws: Support Content-Length in the fsread1 channel
  doc/protocol.md
  pkg/base1/test-external.js
  src/bridge/cockpitfsread.c
  src/bridge/cockpitfsread.h
  src/bridge/test-fs.c
  src/cockpit/channels/filesystem.py
  src/ws/cockpitchannelresponse.c
  test/pytest/mocktransport.py
  test/pytest/test_bridge.py
Labels: release-blocker

#19909 apps: Search in /usr/share/swcatalog
  pkg/apps/watch-appstream.py
  test/verify/check-apps
Labels: release-blocker

#19911 base1: simplify the Content-Length test
  pkg/base1/test-external.js
Labels: no-test
