Repository cockpit-project/cockpit, pull requests merged in 2024-03, with the labels that each got.

#20128 appstream: Fix launchable for Networking
  src/appstream/org.cockpit-project.cockpit-networkmanager.metainfo.xml.in
Labels: no-test

#20130 test: Wait for usage bar before mdraid pixel test
  test/verify/check-storage-mdraid
Labels: flake

#20154 pyproject.toml: stop linting in venvs
  pyproject.toml
Labels: no-test

#20162 bridge: accept `null` for host/group on kill
  src/cockpit/protocol.py
Labels: release-blocker

#20188 misc: move to new tasks container location
  .github/workflows/release.yml
  .github/workflows/weblate-sync-pot.yml
  HACKING.md
Labels: no-test, .github-changes

#20195 workflows: add tasks-container-update workflow
  .github/workflows/tasks-container-update.yml
Labels: no-test, .github-changes

#20211 ci: Don't use "make" in tasks-container-update
  .github/workflows/tasks-container-update.yml
Labels: no-test, .github-changes

#20202 test: Re-download package sets for daily/updates-testing scenarios
  test/run
  test/vm.daily
  test/vm.updates-testing
Labels: no-test

#20215 test: Move TestAD and TestConnection to the "networking" scenario
  test/run
Labels: no-test

#20227 workflows: Move tasks-container-update to Sunday night
  .github/workflows/tasks-container-update.yml
Labels: no-test, .github-changes

#20225 lib: Avoid infinite layout measurements in plots
  pkg/lib/cockpit-components-plot.jsx
Labels: release-blocker

#20231 build: Put .cockpit-ci into source tarballs
  Makefile.am
Labels: release-blocker

#20232 sosreport: Fix command injection with crafted report names [CVE-2024-2947]
  pkg/sosreport/sosreport.jsx
  test/verify/check-sosreport
Labels: release-blocker, release-note

#20233 [rhel-8] sosreport: Fix command injection with crafted report names [CVE-2024-2947]
  pkg/sosreport/sosreport.jsx
  test/verify/check-sosreport
Labels: backport
