Repository cockpit-project/cockpit, pull requests merged in 2024-08, with the labels that each got.

#20841 hosts: Use a cockpit.conf option to disable the host switcher
  configure.ac
  doc/guide/authentication.xml
  doc/man/cockpit.conf.xml
  pkg/shell/indexes.jsx
  pkg/shell/manifest.json
  src/ws/cockpitchannelresponse.c
  src/ws/cockpithandlers.c
  test/common/testlib.py
  test/verify/check-shell-host-switching
  test/verify/check-shell-multi-machine-key
  tools/cockpit.spec
  tools/debian/rules
Labels: release-blocker, release-note

#20853 flatpak: Drop default-branch property from manifest
  containers/flatpak/prepare
Labels: no-test

#20877 lib: Fix race condition in Terminal size calculation
  pkg/lib/cockpit-components-terminal.jsx
Labels: flake

#20887 tmt: drop special-casing for RHEL 8
  test/browser/run-test.sh
Labels: no-test

#20860 login: Prevent multiple logins in a single browser session
  pkg/static/login.js
  src/ws/cockpitauth.c
  src/ws/cockpitauth.h
  src/ws/cockpithandlers.c
  test/verify/check-embed
Labels: release-blocker

#20921 packit: Temporarily disable Fedora 41 tests
  packit.yaml
Labels: no-test

#20923 systemd: Relax cockpit-ws-user.service dependencies
  src/systemd/cockpit-ws-user.service
Labels: release-blocker

#20924 lib: Fix cockpit.file().modify() annotation
  pkg/lib/cockpit.d.ts
Labels: no-test

#20926 pkg: add qunit tests for modify() "" vs null
  pkg/base1/test-file.js
Labels: no-test

#20927 test: Implement "contextmenu" mouse event for BiDi
  test/common/testlib.py
Labels: no-test

#20933 packit: Re-enable Fedora 41
  packit.yaml
Labels: no-test

#20949 test: Adjust TestLogin.testBasic for current coreutils
  test/verify/check-static-login
Labels: blocked, no-test
