Repository cockpit-project/cockpit, pull requests merged in 2025-01, with the labels that each got.

#21495 workflows: Move release and node-modules workflows from Ubuntu 20.04 to 24.04
  .github/workflows/dependabot.yml
  .github/workflows/release.yml
  .github/workflows/reposchutz.yml
Labels: no-test, .github-changes

#21501 login: Beibooting to all supported OSes
  pkg/static/login.js
  src/cockpit/beiboot.py
  src/cockpit/osinfo.py
  test/verify/check-shell-multi-machine
Labels: release-note

#21529 build: Let `make` rebuild the bundle on PO changes
  pkg/Makefile.am
Labels: no-test

#21541 Docs: Add userpass for VM web login
  test/README.md
Labels: no-test

#21555 test: remove empty else clause
  test/common/testlib.py
Labels: no-test

#21561 tools: Drop obsolete glib-networking dependency of bridge
  tools/cockpit.spec
  tools/debian/control
Labels: release-blocker

#21558 containers/ws: Include cockpit-files
  containers/ws/install.sh
Labels: no-test, release-note

#21569 lib: Make DynamicListForm.itemcomponent a component type instead of instance
  pkg/lib/cockpit-components-dynamic-list.jsx
Labels: no-test
