Repository cockpit-project/cockpit, pull requests merged in 2025-03, with the labels that each got.

#21676 lib: Improve http channel debug messages
  pkg/lib/cockpit.js
Labels: no-test

#21692 workflows: adjust stamp checking for dnf 5
  .github/workflows/trigger-anaconda.yml
Labels: no-test, .github-changes

#21694 Cleanup leftover comment
  pkg/storaged/drive/smart-details.jsx
Labels: no-test

#21698 services: translate strings
  pkg/systemd/services.jsx
Labels: release-blocker

#21701 tmt: Don't fail if /dev/nvme* does not exist
  test/browser/browser.sh
Labels: release-blocker, no-test

#21703 lib: Fix http debug message crash
  pkg/lib/cockpit.js
Labels: release-blocker, no-test

#21705 packit: Enable fedora-42 test
  packit.yaml
Labels: no-test

#21707 doc: update fsinfo protocol documentation
  doc/protocol.md
Labels: no-test

#21706 tools: Fix Debian --build={all,any} FTBFS
  tools/debian/rules
Labels: no-test

#21668 Extend testlib typing
  pyproject.toml
  test/common/storagelib.py
  test/verify/check-storage-nfs
Labels: blocked

#21720 workflows: obtain the last field and not line of dnf output
  .github/workflows/trigger-anaconda.yml
Labels: no-test, .github-changes

#21766 tests: fix minimum required libblockdev version check
  test/verify/check-storage-smart
Labels: no-test

#21785 packagekit: Fix tracer comment
  pkg/packagekit/updates.jsx
Labels: no-test

#21756 test: Wait until toolbar is rendered before taking a screenshot
  test/verify/check-metrics
Labels: no-test

#21777 failures: Update grid of early failure page
  pkg/shell/failures.tsx
Labels: page:shell

#21775 bridge: Implement pidfd watching manually
  src/cockpit/transports.py
  test/pytest/test_transport.py
Labels: unrelated-test-failure

#21793 Revert "storage: Use mdraid metadata version 1.0 when in Anaconda mode"
  pkg/storaged/mdraid/create-dialog.jsx
  test/verify/check-storage-anaconda
  test/verify/check-storage-mdraid
Labels: release-blocker, unrelated-test-failure

#21798 tls: Fix inconsistent spaces in self-signed SSL certificate
  src/tls/cockpit-certificate-helper.in
Labels: no-test

#21789 lib: Password field help button to inline button
  pkg/lib/cockpit-components-password.jsx
Labels: no-test
